### ISSUE TITLE
[Feature Request] Compatibility with react-admin

### ISSUE THREAD

**Issue by thclark** [creativetimofficial/material-dashboard-react#101]
### What is your enhancement?
The biggest problem with ct-material-dashboard-react-pro is that as developers, we still have to wire everything up - from state management to wrapping containers around components and declaring sagas, as well as properly wiring up forms and auth.

However, [react-admin](https://github.com/marmelab/react-admin) is an excellent library that handles all of this for you out of the box, relying on proven tech for sagas, forms, auth and fetching data from an API.

Providing material-dashboard-react as a theme (plus perhaps a few custom components like sidebar and navbar etc) would take all the pain out of bootstrapping an app. Also, it leaves you entirely backend-agnostic (avoiding the need for a more complete example to actually choose a backend like PHP or django).

My own use case for this is that I have an app in material-dashboard-pro, and an app now in react-admin. Using what I've learned from creative-tim, I've restyled the other app, but it's still quite materially.

I want to: 
 - Take the horrid tech stack underneath my ct-material-dashboard-pro app, and replace it with the much more maintainable react-admin framework, without using the CT styling that users are already enjoying
 - Take my non-ct-material-dashboard-pro app and apply some creative-tim magic to it.

Hope this helps.

**Comment by EINazare** [comment]
Hello @thclark ,

At the moment we haven't worked with react-admin, and can't really give you guidance on how to use it.

Best,
Manu

**Comment by thclark** [comment]
Hi @EINazare, I think it was fairly clear I wasn't asking for help, but submitting suggestion for enhancement with a use case.

I spent a not-that-small part of my day submitting the above issue because I felt it was something that:
 - could be a lot of value to other clients
 - powerfully complement other aspects of your business development such as AppSpeed
 - ... and therefore be of a lot of value to Creative Tim.

There's really no benefit to me - I've already ported styling across to RA. Look into it, or don't, that's your call - but it would've been nice to have had a thanks for taking the time to carefully craft some useful feedback.

**Comment by EINazare** [comment]
Hello again, @thclark ,

The confusion came from this:

> 
> I want to:
> 
> * Take the horrid tech stack underneath my ct-material-dashboard-pro app, and replace it with the much more maintainable react-admin framework, without using the CT styling that users are already enjoying
> * Take my non-ct-material-dashboard-pro app and apply some creative-tim magic to it.
> 

My bad for misunderstanding your issue.

Best,
Manu
