### ISSUE TITLE
Display text when mouseover on the Button

### ISSUE THREAD

**Issue by dattajoshi** [creativetimofficial/material-dashboard-react#103]
Hi,

I have used the Button Component and I want to display a small text when I mouseover on the button. I don't see any example in the demo nor in the purchased the product. 

Example:

<Button
          justIcon
         color="rose"
         onClick={() => {
                                     //doSomething
                                   }
                        }
>
</Button>

Help is greatly appreciated.

Thanks

**Comment by EINazare** [comment]
Hello there, @dattajoshi ,

We only have this sample codes: https://demos.creative-tim.com/material-dashboard-react/#/documentation/tooltips

Best,
Manu

**Comment by navyarao04** [comment]
@EINazare Thanks, that worked

**Comment by dattajoshi** [comment]
@EINazare Thanks, It worked
