### ISSUE TITLE
[Bug] Issue with routing

### ISSUE THREAD

**Issue by Ludea** [creativetimofficial/material-dashboard-react#106]
### Version
1.8.0
### Reproduction link
https://codepen.io/ludea/pen/qBBqvoR.js
### Operating System
Windows / Android 
### Device
Pc / smartphone 
### Browser & Version
Latest Chrome 
### Steps to reproduce
Into routes.js,  modify layout prop like '#', and modify into Admin.js layout, `if(prop.layout === '#')'

### What is expected?
When accessing views, the components are not rendered, and on the navbar, 2 views are selected. 
### What is actually happening?
Render the component into a view

---

**Comment by EINazare** [comment]
Hello there, @Ludea ,

The `#` is a reserved word for hash routing or for id's in pages.
You can not change the Admin layout to `#`, you should use a word, like we've used `admin` word.

Hope this helps.

Best,
Manu

**Comment by Ludea** [comment]
If if use a simple word, or no words, I have the same issue.
My goal is to delete layout path to have something like `localhost/`, `localhost/#/foo`

**Comment by EINazare** [comment]
Hello again, @Ludea ,

If you change all "/admin" or "admin" words to "/foo" or "foo" everything should work and the admin links should be rendered on "/foo/route-name". Are you saying that this does not work?
You cannot have `/` routes, the layouts need a specific route, such as `admin` or `auth`.

Best,
Manu

**Comment by Ludea** [comment]
Yes, with another word as `/foo` it is not working.
I add `/foo` into routes.js (into `layout`) and into Admin.js ( `if (prop.layout === "/foo")` and ```const getRoute = () => {
    return window.location.pathname !== "/foo/maps";
  };```)

**Comment by Ludea** [comment]
Also I delete `Redirect` component into Admin.js and index.js but I thinks it doesn't matter

**Comment by EINazare** [comment]
Hello again, @Ludea ,

On my machine, everything works properly.
Please download again the project, and change all `/admin` to `/smth`. You will see that everything works fine. I believe there may be some other changes that you have made and those could make this not work. But once again, download again, change `/admin` to `/smth` and see if it works - no other changes.

Best,
Manu
