### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by cherchyk** [creativetimofficial/material-dashboard-react#108]
Hi,

What this problem can be?

```
$ npm install
npm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! Unexpected end of JSON input while parsing near '...df6800c74af0a606c719e'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-11-18T03_28_22_649Z-debug.log
```

**Comment by EINazare** [comment]
Hello there, @cherchyk ,

Please provide the following video (you will need to use a sharing tool, such as https://wetransfer.com/):
* Download the product
* Unzip the product
* Open terminal and cd into the project
* Run npm run install:clean
* Showcase the issue

Will wait for the mentioned video.

Best,
Manu
