### ISSUE TITLE
Scroll not working in documentation site

### ISSUE THREAD

**Issue by steodor** [creativetimofficial/material-dashboard-react#109]
### Version
1.8.0
### Reproduction link
https://demos.creative-tim.com/material-dashboard-react/#/documentation/tutorial
### Operating System
Windows 10
### Device
PC
### Browser & Version
Chrome 79.0.3945.117
### Steps to reproduce
1. Open the free Material Dashboard theme from here: https://themes.material-ui.com/
2. Click on the Documentation button in the menu on the right side of the page
3. Try to scroll the main content (where it exceeds window height, try multiple categories from the left navigation menu)

### What is expected?
scroll so i can actually read the docs
### What is actually happening?
not scrolling

---

**Comment by EINazare** [comment]
Hello there, @steodor ,

Thank you for your interest in working with our products.
I've made a quick test, and it seems that the scroll is working.
Can you please tell us if the scroll on your device is working on these websites:

- https://material-ui.com/
- https://getbootstrap.com/
- https://demos.creative-tim.com/argon-dashboard-react/#/documentation/forms

I am trying to figure our if this is only on our product, or maybe there is something else.

Best,
Manu

**Comment by steodor** [comment]
Hi @EINazare , yes, it's working on all 3 sites you linked to. Also, it works fine on the very similar Material Kit docs here: https://demos.creative-tim.com/material-kit-react/#/documentation/tutorial so it seems like it's an isolated issue. Thanks :)

**Comment by EINazare** [comment]
Hello again, @steodor ,

I forgot to ask what were you using, the trackpad or a mouse?
Also, if you manually drag the left cursor, does the scroll work?

Best,
Manu

**Comment by steodor** [comment]
@EINazare sorry for the delay. Using a mouse, and no :) However, i did discover another way to reproduce:

1. go to https://demos.creative-tim.com/material-dashboard-react/#/documentation/tutorial directly, in a new tab (observe that scroll works just fine in the main content of the page)
2. click on the "Material Dashboard React" link in the header
3. click Back to return to the docs - scroll is broken
Here's a video of the scenario: https://www.screencast.com/t/KlQnykLN

Also, the initial steps can be reproduced in a similar way, but on step 3 instead of going Back, press the Documentation button in the right-hand side menu.
Here's a video of this scenario: https://www.screencast.com/t/tcQYCNBgzW

Looking at the Elements panel in DevTools makes the issue clear, just look at the `<body>` tag while reproducing the issue. The theme sets a `style="overflow: hidden;"` attribute to the `<body>` tag, which is not cleared on subsequent same-page navigation back to the docs (via back/docs button). A page refresh clears it so the scroll is working again. It might have something to do with `perfect-scroll` which i see is used on the main content of the dashboard theme? Anyway it should be pretty easy to fix.
Oh, here's a video for this as well: https://www.screencast.com/t/jB2vuK0LHIXz

Have fun :)

**Comment by EINazare** [comment]
Hello again, @steodor ,

Just made a quick redeploy on our live preview.
The issue should now be solved.

Best,
Manu
