### ISSUE TITLE
Using class properties not implemented in MUI components

### ISSUE THREAD

**Issue by hackedbellini** [creativetimofficial/material-dashboard-react#11]
When running this in my webpack configuration I had this happening:

```
Warning: Material-UI: the key `rootLabelIcon` provided to the classes property is not implemented in Tab.
You can only override one of the following: root,labelIcon,textColorInherit,textColorPrimary,textColorPrimarySelected,textColorPrimaryDisabled,textColorSecondary,textColorSecondarySelected,textColorSecondaryDisabled,textColorInheritSelected,textColorInheritDisabled,fullWidth,wrapper,labelContainer,label,labelWrapped

Warning: Material-UI: the key `rootInheritSelected` provided to the classes property is not implemented in Tab.
You can only override one of the following: root,labelIcon,textColorInherit,textColorPrimary,textColorPrimarySelected,textColorPrimaryDisabled,textColorSecondary,textColorSecondarySelected,textColorSecondaryDisabled,textColorInheritSelected,textColorInheritDisabled,fullWidth,wrapper,labelContainer,label,labelWrapped

Warning: Material-UI: the key `inkbar` provided to the classes property is not implemented in Input.
You can only override one of the following: root,formControl,focused,disabled,underline,error,multiline,fullWidth,input,inputMarginDense,inputDisabled,inputMultiline,inputType,inputTypeSearch
```

I don't know why this doesn't happen when running `react-scripts start`, but looking at the MUI code from `beta36` I noticed that the components actually don't have those properties. They are defined inside their `.d.ts` counterparts, but I don't think that `react-scripts` are considering those...

Either way, I noticed that those props were actually removed after from the `.d.ts` so it is better to use the right ones even now.

I'm about to open a PR that will solve this.

**Comment by EINazare** [comment]
Hello @hackedbellini ,

And thank your for your interest in using our product. 
Sorry for the late response, this is due to the fact that our product is using material-ui@1.0.0-beta34 and not beta 36. In beta 34 we have those properties.
Today or next week we are going to make an update to the latest version of material-ui (beta 41, or beta 42 if they are going to launch beta 42 before our update).

Best,
Manu

**Comment by hackedbellini** [comment]
Hi @EINazare 

Actually this was an issue even in `beta34`. Like I described, the properties are not in the `.js` files but only in the `.ts` files. Don't know if the `react-scripts` were using the `.ts`, but when using my custom webpack deployment I was getting those issues.

If you are going to update to the latest `mui` maybe you should take a look at my PRs first? I created a PR about 2 weeks ago updating this to the latest mui of that day: #13 

Note that that PR requires my #12 to work also. I could have add both patches in the same PR, but wanted to separate this "already existing issue" from the "update mui" one.

**Comment by EINazare** [comment]
Hello @hackedbellini ,

I've seen your PR and we are going to do the same as you've done in your [#12](https://github.com/creativetimofficial/material-dashboard-react/pull/12). 
In the [#13](https://github.com/creativetimofficial/material-dashboard-react/pull/13), i've seen some changes which i think it's a matter of choice, and not going to add in our code.

Best,
Manu

**Comment by hackedbellini** [comment]
@EINazare what exactly is a matter of choice? All changes there were made to keep the previous behavior.

If you are talking about the `spacing=16`, which is one change that looks like "a matter of choice", in `v1.0.0-beta.39` they changed the default spacing from `16` to `0` and, whithout this, you theme would break. Try to `CTRL+F` for `spacing` in this page: https://github.com/mui-org/material-ui/releases.

Again, all I've done was to fix api changes to make your theme continuing to work and keep the same behavior/look'n'feel. All of them were described in the releases page also
