### ISSUE TITLE
[Bug] Compilation error when installing via npm

### ISSUE THREAD

**Issue by yoliva** [creativetimofficial/material-dashboard-react#110]
### Version
1.8.0
### Reproduction link
https://codesandbox.io/s/goofy-brahmagupta-qtyr2
### Operating System
Windows 10
### Device
Laptop
### Browser & Version
Chrome - 79.0.3945.130
### Steps to reproduce
1- create react project using npx create-react-app
2- install material dashboard via: "npm i material-dashboard-react"
3- add a button to the App.js file

### What is expected?
I expect to see the button properly rendered
### What is actually happening?
I'm getting a compilation error:

Failed to compile.

./node_modules/material-dashboard-react/src/components/CustomButtons/Button.js
SyntaxError: \node_modules\material-dashboard-react\src\components\CustomButtons\Button.js: Unexpected token (44:4)

  42 |   });
  43 |   return (
> 44 |     <Button {...rest} classes={muiClasses} className={btnClasses}>
     |     ^
  45 |       {children}
  46 |     </Button>
  47 |   );

---

**Comment by EINazare** [comment]
Hello there, @yoliva ,

Please read this thread here: https://github.com/creativetimofficial/ct-material-dashboard-pro-react/issues/50#issuecomment-407030675
We'll try to solve this issue as soon as possible.

Best,
Manu

**Comment by vvinogradsky** [comment]
I am also trying to get going with a basic setup and having the same issue. The thread you are referring to suggests adding two directories under /src but that doesn't help. Just empty directories? What next? Do I need to make changes to package.json? The dependency on material-dashboard-react is already there:
"material-dashboard-react": "^1.8.0"

Really, the basic setup with  npx create-react-app / npm i material-dashboard-react is not something people should be pulling their hair out. Can you give specific and working instructions?

**Comment by jiasuan** [comment]
I'm facing the same issues while importing the Button  installing using "npm i material-dashboard-react". Has anyone got idea how to fix this issue?

![image](https://user-images.githubusercontent.com/38315168/83935188-ce627900-a7e9-11ea-98ac-b8fcece2017f.png)

**Comment by sajadevo** [comment]
**Hi there**

We've just updated the product now it has a new look with a flexible structure.

**All the best**
**Sajad**
