### ISSUE TITLE
Docker Question

### ISSUE THREAD

**Issue by Buttered** [creativetimofficial/material-dashboard-react#112]
Just curious if anyone has been able to get this running in docker or if there's any documentation to follow to do so?

I've been struggling for a few days now attempting to get it working properly.

Thanks

**Comment by EINazare** [comment]
Hello there, @Buttered ,

We haven't yet worked with Docker.
Is any of these links helpful to you:

- https://dev.to/ziv/dockerize-create-react-app-in-3-minutes-3om3
- https://medium.com/@shakyShane/lets-talk-about-docker-artifacts-27454560384f

Best,
Manu

**Comment by Buttered** [comment]
I'll take a look at them.

Currently my Dockefile looks as such...

# Build the Go API
FROM golang:latest AS builder
ADD . /app
WORKDIR /app/server
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-w" -a -o /main .


# Build the React Application
FROM node:12.14.1-alpine AS node_builder
COPY --from=builder /app/webapp ./
RUN npm install
RUN npm run build


# Production container
FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /main ./
COPY --from=node_builder /build ./web
RUN chmod +x ./main
EXPOSE 3000
CMD ./main

**Comment by Buttered** [comment]
i believe it's an issue with the line in Production container "COPY --from=node_builder /build ./web

It seems like the template does not create a build folder?

**Comment by EINazare** [comment]
Hello again, @Buttered ,

Please refer to our live docs for all available command that come with this product: https://demos.creative-tim.com/argon-dashboard-react/#/documentation/build-tools

Really sorry, but since I haven't worked wit docker, I do not know what guidance to give you.

Best,
Manu

**Comment by Buttered** [comment]
My mistake, there is a build folder, it just doesn't seem to work with docker?

**Comment by Buttered** [comment]
documentation for this would be nice as majority of all applications are now ran via docker/kubernetes

**Comment by Macorreag** [comment]
Hello, @Buttered did you migrate to docker this project?

**Comment by alebeta90** [comment]
Hi friends,

I have it working with docker I can share my working Dockerfile with you

```
# pull official base image
FROM node:13.12.0-alpine as build

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# Copy Repo
COPY . ./
RUN npm install --silent
RUN npm run build
RUN ls -lh

FROM nginx:1.17-alpine

COPY --from=build /app/build /usr/share/nginx/html

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

VOLUME /usr/share/nginx/html

VOLUME /etc/nginx


 # Don't run as root
USER 101

EXPOSE 8080
```

keep in mind that I'm passing custom nginx config, you could pass your own too or just use the default.

**Comment by sajadevo** [comment]
**Hi there**

We've just updated the product now it has a new look with a flexible structure.

**All the best**
**Sajad**
