### ISSUE TITLE
can't refresh page in server after build

### ISSUE THREAD

**Issue by evaniac** [creativetimofficial/material-dashboard-react#113]
cant refresh page in server after build. teh problem is internal server error. after build the project what needs to be adjusted(htaccess or code in project?)

**Comment by EINazare** [comment]
Hello there, @evaniac ,

This is not a bug with our products, but rather with React and React-Scripts, to solve this you can either change the BrowserRouter with HashRouter, or change the webpack config: https://stackoverflow.com/questions/49189880/blank-page-when-refreshing-in-react-router

Best,
Manu
