### ISSUE TITLE
can't add paid material-dashboard-react

### ISSUE THREAD

**Issue by moolotfy** [creativetimofficial/material-dashboard-react#116]
i got this message 

> material-dashboard-pro-react@1.8.0 start G:\MERN Stack\material-dashboard-pro-react-v1.8.0_2
> NODE_PATH=./src react-scripts start

'NODE_PATH' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! material-dashboard-pro-react@1.8.0 start: `NODE_PATH=./src react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the material-dashboard-pro-react@1.8.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:

**Comment by EINazare** [comment]
Hello there, @moolotfy ,

Please follow our rules of opening a Github issue: 
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/material-dashboard-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->
```

Best,
Manu
