### ISSUE TITLE
[Bug] i cannot add Martial Dashboard to my project

### ISSUE THREAD

**Issue by moolotfy** [creativetimofficial/material-dashboard-react#121]
### Version
1.8.0
### Reproduction link
https://codepen.io/mohamed-adel-lotfy/pen/eYpoOXX
### Operating System
windows
### Device
Lenovo
### Browser & Version
Chrome latest version
### Steps to reproduce
after add "Component" Not added
### What is expected?
to work
### What is actually happening?
Module not found: Can't resolve 'assets/jss/material-dashboard-pro-react/components/buttonStyle.js'

Error from chokidar (G:\): Error: EBUSY: resource busy or locked, lstat 'G:\pagefile.sys'

---

**Comment by EINazare** [comment]
Hello there, @moolotfy ,

Are any of these links helpful to you:
- https://demos.creative-tim.com/material-dashboard-react/#/documentation/tutorial (there is a special section for `Module not found` errors)
- https://github.com/creativetimofficial/ct-material-dashboard-pro-react/issues/50#issuecomment-407030675

Best,
Manu

**Comment by moolotfy** [comment]
Why doesn't there "documentation" for browsing the paid library like the
demo version like the "material-dashboard-react" library, I have a big
problem adding items

**Comment by EINazare** [comment]
Hello again, @moolotfy ,

I do not follow your last email.
Please rephrase it, or give me some additional notes.

Best,
Manu
