### ISSUE TITLE
[Feature Request] Profile form add Select to it

### ISSUE THREAD

**Issue by alebeta90** [creativetimofficial/material-dashboard-react#125]
### What is your enhancement?
Hi,

am using this nice template, and I would like to use Select inside of the profile section. I can see that form was done using CustomInput component, I would like to know if there is something similar for Select field.

thanks in advance

**Comment by EINazare** [comment]
Hello there, @alebeta90 ,

Unfortunately, the Select is part of our PRO paid version.
You can check it here: 
- https://www.creative-tim.com/product/material-dashboard-pro-react
- https://demos.creative-tim.com/material-dashboard-pro-react/#/admin/extended-forms

Hope you are ok with me closing this issue.

Best,
Manu
