### ISSUE TITLE
[Feature Request] Version for Nextjs

### ISSUE THREAD

**Issue by pablotdv** [creativetimofficial/material-dashboard-react#126]
### What is your enhancement?
There are a version for nextjs?

**Comment by EINazare** [comment]
Hello there, @pablotdv ,

At the moment we do not have a NextJS version for the product at hand.
Please check our marketplace for more information: https://www.creative-tim.com/templates/nextjs

Best,
Manu

**Comment by EINazare** [comment]
Hello there, @pablotdv ,

You can check the NextJS version here: https://www.creative-tim.com/product/nextjs-material-dashboard

Best,
Manu
