### ISSUE TITLE
React class base components instead Hooks

### ISSUE THREAD

**Issue by digital230** [creativetimofficial/material-dashboard-react#129]
### What is your enhancement?
Hi, i am not comfortable with Hooks, can i get class base theme

**Comment by EINazare** [comment]
Hello there, @digital230 ,

Unfortunately, we only have the hooks version.

Best,
Manu

**Comment by digital230** [comment]
Hi, well this is very bad . React is not going to revoke it support for class base components. i moved to old branch for react component base code.
