### ISSUE TITLE
[Bug] Cannot find module: 'material-dashboard-react'

### ISSUE THREAD

**Issue by sergiogcharles** [creativetimofficial/material-dashboard-react#131]
### Version
1.9.0
### Reproduction link
https://codesandbox.io/s/gallant-tharp-sut75?file=/src/App.js
### Operating System
MacOS Mojave 10.14.6
### Device
MacBook Pro
### Browser & Version
Chrome - 75.0.3770.142
### Steps to reproduce
1- create react project using `npx create-react-app`
2- install material dashboard via: `npm i --save material-dashboard-react`
3- add a button to the `App.js` file
4- npm run build
### What is expected?
I expect to be able import components from material-dashboard-react', e.g. `import { Button } from 'material-dashboard-react';`
### What is actually happening?
I'm getting a compilation error:
Cannot find module: 'material-dashboard-react'. Make sure this package is installed.

Failed to compile.

---

**Comment by sergiogcharles** [comment]
@EINazare I looked at #110, but this doesn't seem to have been solved?

**Comment by EINazare** [comment]
Yes, please continue the discussion there.

**Comment by bashiryousufy** [comment]
Any solution for this?

**Comment by sajadevo** [comment]
Hey @bashiryousufy,

The product is not available as npm package you need to clone it or download it as zip file and then put it into you project.

Cheers,
Sajad
