### ISSUE TITLE
[Bug] Active sidebar function suggestion

### ISSUE THREAD

**Issue by lim1017** [creativetimofficial/material-dashboard-react#133]
### Version
    "@material-ui/core": "4.11.0",
### Reproduction link
https://jsfiddle.net/    not needed
### Operating System
linux
### Device
laptop
### Browser & Version
chrome
### Steps to reproduce

Creating a sidebar route
Create a sidebar route named /companyprofile 
and have another route to a different page /company. (not intended to be navigated to by sidebar)

### What is expected?

going to /company should not highlight the /companyprofile in the sidebar

### What is actually happening?
going to /company would result in the sidebar behind "active".  even though the sidebar route is /companyprofile.

I can see other bugs occuring with the sidebar routes when they have similar names as well, although I did not personally run to them.

---
### Solution

In the sidebar, you have the following function
  
function activeRoute(routeName) {
  return window.location.href.indexOf(routeName) > -1 ? true : false;
}

replace with
return window.location.href.endsWith(routeName) ? true : false;

I think this is less likely to cause the above or any error as it is more precise?

**Comment by EINazare** [comment]
Hello there, @lim1017 ,

Is this `return window.location.href.endsWith(routeName) ? true : false;` supported in all major browsers?
- Safari
- Safari Mobile
- Google Chrome (Mac & Windows)
- Google Chrome Mobile (Android & iOS)
- Firefox (Mac & Windows)
- Edge

We'll take a look at this in our next update, but maybe you already know this.

Best,
Manu

**Comment by lim1017** [comment]
I do not know sorry.  It was just something I came accross while using the dashboard

**Comment by EINazare** [comment]
Ok, we'll take a look in our next update.

**Comment by bavoceulemans** [comment]
> Hello there, @lim1017 ,
> 
> Is this `return window.location.href.endsWith(routeName) ? true : false;` supported in all major browsers?
> 
> * Safari
> * Safari Mobile
> * Google Chrome (Mac & Windows)
> * Google Chrome Mobile (Android & iOS)
> * Firefox (Mac & Windows)
> * Edge
> 
> We'll take a look at this in our next update, but maybe you already know this.
> 
> Best,
> Manu

endWith was added in ECMAScript 2015 and has 97.98% support on browsers so this change can be made without losing support. [Source](https://caniuse.com/?search=endsWith)
