### ISSUE TITLE
[Bug] Getting values of textbox in LoginPage and using them in Get-stared button on-click event

### ISSUE THREAD

**Issue by Bazarganigilani** [creativetimofficial/material-dashboard-react#135]
### Version
1.9.0
### Reproduction link
https://www.creative-tim.com/product/material-kit-pro-react
### Operating System
Windows
### Device
Windows
### Browser & Version
Chrome (latest)
### Steps to reproduce
Finding the textbox values of login page boxes
### What is expected?
Finding the textbox values of login page boxes
### What is actually happening?
Finding the textbox values of login page boxes

---
### Solution
Hi,

I am using the login page of above product and I would like to know how to use editbox texts like for name and email inside an event for GET STARTED button,

I would like to simply get the values of textboxes and use them inside onClick event for above button?

Can someone guide me how to do that?

**Comment by EINazare** [comment]
Hello there, @Bazarganigilani ,

We haven't used Textbox inside our product, I've checked the live docs of Material UI and it seems that they do not have a TextBox component either.
Can you please clarify this a bit?
Are you looking for the TextField of Material-UI: https://material-ui.com/api/text-field/#textfield-api?

Best,
Manu

**Comment by Bazarganigilani** [comment]
Hi,

I am trying to capture first name email and passwords of textboxes in the LOG-IN page

I am using onchange event as follow:

```
<CustomInput
                      id="first"
                      formControlProps={{
                        fullWidth: true
                      }}
                      inputProps={{
                        onChange: change1,
                        defaultValue: 'mahdi',
                        value: '',
                        placeholder: "First Name...",
                        type: "text",
                        startAdornment: (
                          <InputAdornment position="start">
                            <Face className={classes.inputIconsColor} />
                          </InputAdornment>
                        )
                      }}
                    />


```But in the event I can't capture any text property of textboxes

```
  function change1(v)
  {
    console.log(v);
    set_fname(v)
  }
```

**Comment by EINazare** [comment]
Hello again, @Bazarganigilani ,

And it does not work? It seems correct to me, if not, maybe try:
```
onChange: e => change1(e)
```
?

Best,
Manu

**Comment by Bazarganigilani** [comment]
yes, but how to get vale from above e?

i log the e in the function but it doesnt have any value inside

```
SyntheticEvent {dispatchConfig: {…}, _targetInst: FiberNode, _dispatchInstances: FiberNode, nativeEvent: InputEvent, _dispatchListeners: ƒ, …}
bubbles: (...)
cancelable: (...)
currentTarget: (...)
defaultPrevented: (...)
dispatchConfig: null
eventPhase: (...)
isDefaultPrevented: (...)
isPropagationStopped: (...)
isTrusted: (...)
nativeEvent: (...)
target: (...)
timeStamp: (...)
type: (...)
_dispatchInstances: null
_dispatchListeners: null
_targetInst: null
preventDefault: (...)
stopPropagation: (...)
get bubbles: ƒ ()
set bubbles: ƒ (val)
get cancelable: ƒ ()
set cancelable: ƒ (val)
get currentTarget: ƒ ()
set currentTarget: ƒ (val)
get defaultPrevented: ƒ ()
set defaultPrevented: ƒ (val)
get eventPhase: ƒ ()
set eventPhase: ƒ (val)
get isDefaultPrevented: ƒ ()
set isDefaultPrevented: ƒ (val)
get isPropagationStopped: ƒ ()
set isPropagationStopped: ƒ (val)
get isTrusted: ƒ ()
set isTrusted: ƒ (val)
get nativeEvent: ƒ ()
set nativeEvent: ƒ (val)
get target: ƒ ()
set target: ƒ (val)
get timeStamp: ƒ ()
set timeStamp: ƒ (val)
get type: ƒ ()
set type: ƒ (val)
get preventDefault: ƒ ()
set preventDefault: ƒ (val)
get stopPropagation: ƒ ()
set stopPropagation: ƒ (val)
__proto__: Object
```

**Comment by Bazarganigilani** [comment]
Hi,

I figured it out 

e.target.value
