### ISSUE TITLE
[Feature Request] Sample API call with React Table

### ISSUE THREAD

**Issue by NealWalters** [creativetimofficial/material-dashboard-react#138]
### What is your enhancement?
Your templates are great, except they use hard-coded data from /variables/general.js. 
I tried to add a call to my REST API, and got totally lost on how to do that.  I've got my API testing and working separately. 
Do you have any examples?  I have posted what I'm trying to do here: https://stackoverflow.com/questions/63619129/material-ui-fetching-data-display-in-datatable-react-usestate-cannot-be-c/63619346?noredirect=1#comment112503867_63619346, but unsure if the answers I've been given are complete.

**Comment by EINazare** [comment]
Hello again, @NealWalters ,

Please take a look at our FREE NodeJS & React & Material-UI product here: https://www.creative-tim.com/product/material-dashboard-react-nodejs
It was done by a third party company that we've partnered with, and unfortunately, we (at Creative Tim) do not know how an API would work.
You could also take a look at our free tutorials:

- https://www.youtube.com/watch?v=BMPHfnAA9iI&list=PLWxSJr7LCl87rxd7A4j9WEFUbJz4gTNLa
- https://www.youtube.com/watch?v=raKV5Rb8oOM&list=PLWxSJr7LCl87rGlQtTo2PoX8hboUU0R8a
- https://www.youtube.com/watch?v=no2PD2kq-dE&list=PLWxSJr7LCl87OomktWFQVW30QDWtBqFlx

Will leave this issue open for about 30 days, if nobody will be able to help, we'll close it.

Best,
Manu

**Comment by ilmalte** [comment]
@NealWalters I got stuck on this yesterday evening.

For future references here's the solution I've found:
![image](https://github.com/creativetimofficial/material-dashboard-react/assets/17677294/fa01a18b-1203-4224-8762-801483c53588)

Head's up, it's my second day with React so there might be nicer solutions.
