### ISSUE TITLE
inkbar warnings due to "not implemented in input"

### ISSUE THREAD

**Issue by jsmith-phoenix** [creativetimofficial/material-dashboard-react#14]
Hello,
I am seeing the warning below spam the console. Any insights into this? the inkbar seems to be heavily used.

Warning: Material-UI: the key `inkbar` provided to the classes property is not implemented in Input.
You can only override one of the following: root,formControl,focused,disabled,underline,error,multiline,fullWidth,input,inputMarginDense,inputDisabled,inputMultiline,inputType,inputTypeSearch

**Comment by EINazare** [comment]
Hello @jsmith-phoenix ,

Could you please show me your `dependencies` from your `package.json`?

Best,
Manu

**Comment by Doloros** [comment]
Same here.
The package.json : {
  "name": "material-dashboard-react",
  "version": "1.1.0",
  "description": "Material Dashboard React. Coded by Creative Tim",
  "private": false,
  "main": "index.js",
  "dependencies": {
    "ajv": "^6.4.0",
    "chartist": "^0.10.1",
    "classnames": "^2.2.5",
    "material-ui": "^1.0.0-beta.34",
    "material-ui-icons": "1.0.0-beta.17",
    "npm-run-all": "^4.1.1",
    "perfect-scrollbar": "^1.3.0",
    "react": "^16.3.1",
    "react-chartist": "^0.13.1",
    "react-dom": "^16.3.1",
    "react-google-maps": "^9.4.5",
    "react-json-view": "^1.16.1",
    "react-router-dom": "^4.2.2",
    "react-scripts": "1.0.17",
    "react-swipeable-views": "^0.12.12",
    "unstated": "^1.2.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/creativetimofficial/material-dashboard-react.git"
  },
  "keywords": [],
  "author": "Creative Tim <hello@creative-tim.com> (https://www.creative-tim.com/)",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/creativetimofficial/material-dashboard-react/issues"
  },
  "homepage": "https://creativetimofficial.github.io/material-dashboard-react/#/dashboard"
}

**Comment by EINazare** [comment]
@Doloros i've seen a part of the problem. Please do the following to solve this issue:

- delete `node_modules` folder from your project
- change line `"material-ui": "^1.0.0-beta.34",` to `"material-ui": "1.0.0-beta.34",` in package.json

This should do the trick. The thing is that `"material-ui": "^1.0.0-beta.34", will install on your machine some other version of material-ui, other than `1.0.0-beta.34`, and on the newer versions the guys from material-ui it seems that have dropped the key `inkbar`.
For the moment we are going to leave our product on `1.0.0-beta.34`, and when they reach a stable `1.0.0` version we are going to update our product as well.

Let me know if with the changes given, everything works fine.

Best,
Manu

**Comment by windgaucho** [comment]
@EINazare I had the same problem with ```"materia-ui": ^1.0.0-beta.41``` change to ```"1.0.0-beta.34" ``` and now the warnings are gone.

**Comment by Doloros** [comment]
Perfect, thanks !

**Comment by hackedbellini** [comment]
Guys,

**Comment by hackedbellini** [comment]
This is the same problem described here (https://github.com/creativetimofficial/material-dashboard-react/issues/11) and fixed here (https://github.com/creativetimofficial/material-dashboard-react/pull/12).
