### ISSUE TITLE
[Feature Request] package.lock.json should not be in gitignore

### ISSUE THREAD

**Issue by mortezashojaei** [creativetimofficial/material-dashboard-react#143]
### What is your enhancement?
Hi , ignoring this file can make some problems in installing project packages.

i think we should delete package.lock.json from gitignore list.

**Comment by EINazare** [comment]
Hey there, @mortezashojaei ,

Thank you for your feedback and your issue.
We'll add the `package-lock.json` in the next update, after we're going to make some tests.
For example, check if the `package-lock.json` generated on a Mac machine will work on a Windows/Linux/Ubuntu machine.
If that will have no negative effect, then we'll keep the package-lock inside the product.

Best,
Manu
