### ISSUE TITLE
[Help Wanted] Node-sass issue in docker

### ISSUE THREAD

**Issue by heteibako** [creativetimofficial/material-dashboard-react#145]
### Version
1.9.0
### Reproduction link
http://localhost:3000
### Operating System
Mac Osx BigSur
### Device
MacBook Pro 15 retina
### Browser & Version
Chrome latest
### Steps to reproduce
Running the the app in a dockerized container
then I get this error:
Failed to compile.
./src/assets/scss/material-dashboard-pro-react.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-6-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-4!./src/assets/scss/material-dashboard-pro-react.scss)
To import Sass files, you first need to install node-sass.
Run `npm install node-sass` or `yarn add node-sass` inside your workspace.
### What is expected?
The React app runs in the docker environment
### What is actually happening?
The compile process results to fail

---
### Solution
My Dockerile looks like this

FROM node:10
# Create app directory
WORKDIR /app
COPY package*.json ./

COPY . .
RUN npm install
RUN npm rebuild node-sass
RUN npm run build
EXPOSE 3000
CMD ["npm", "start" ]

**Comment by EINazare** [comment]
Hello there, @heteibako ,

Thank you for your interest in working with our products.
Unfortunately, we haven't worked with Docker as of the moment, and we cannot help you with this.

We'll leave the issue open, and maybe someone from our community will come to your rescue.

Best,
Manu

**Comment by heteibako** [comment]
Hi, thanks for your answer.
I have managed to solve the issue. It comes out that the google-maps-react package caused the issue. After removing it from the package.json and ran a clean install, I was able to run the container. 
Not sure how this nom package relates to the issue but definitely working.
Also can be that an update would have solved the issue. Did not try it though.

**Comment by EINazare** [comment]
Nice, thank you for the details.
On our next update, we were planning to drop the usage of react-google-maps, they seem not to be maintained anymore.
