### ISSUE TITLE
[Bug] I can't get it to work in production

### ISSUE THREAD

**Issue by mggRF** [creativetimofficial/material-dashboard-react#149]
### Version
v1.9.0
### Reproduction link
https://man.gastronomundo.com/login
### Operating System
Centos
### Device
VPS
### Browser & Version
Crome.../Firefox....
### Steps to reproduce

https://man.gastronomundo.com/interno/ ,
### What is expected?
It should present the login object
### What is actually happening?
 it is redirecte tohttps://man.gastronomundo.com/interno/login but.....error(404 not Found)

---
### Additional comments
I have modified index.js with

**

<Route exact path= {CARPETA + '/login'} component={LoginScreen} />
<Route exact path= {CARPETA + '/logout'} component={Logout} />
<Route exact path= {CARPETA + '/register'} component={RegisterComponent} />

  <Route  path={CARPETA} component={Admin} />
  <Redirect exact path="/" to={CARPETA} />
  <Route component={p404} />**
(CARPETA = /interno)
In tests (localhost: 3000) it works perfectly, but when I upload it to production and put it behind nginx, I can't find the modules ... not even the login one to which it is forked automatically

**Comment by EINazare** [comment]
Hello there, @mggRF ,

Please delete or configure to your own domain the `homepage` prop from inside the `package.json` file.

Best,
Manu

**Comment by mggRF** [comment]
**Package.json**
name": "wolprayRestaurant_v00",
    "version": "0.1.0",
    "homepage": "/interno",
    "description": "Sistema de mantenimiento para wolpray restaurant",
    "private": false,
    "main": "dist/index.js", ....

**nginx.conf**
server {
		server_name man.gastronomundo.com www.man.gastronomundo.com;
		listen 51.210.241.194;
		root /home/gastronomundo/public_html;
		index index.html index.htm index.php;
		access_log /var/log/virtualmin/man.gastronomundo.com_access_log;
		error_log /var/log/virtualmin/man.gastronomundo.com_error_log;
		fastcgi_param GATEWAY_INTERFACE CGI/1.1;
		fastcgi_param SERVER_SOFTWARE nginx;
		fastcgi_param QUERY_STRING $query_string;
		fastcgi_param REQUEST_METHOD $request_method;
		fastcgi_param CONTENT_TYPE $content_type;
		fastcgi_param CONTENT_LENGTH $content_length;
		fastcgi_param SCRIPT_FILENAME /home/gastronomundo/public_html$fastcgi_script_name;
		fastcgi_param SCRIPT_NAME $fastcgi_script_name;
		fastcgi_param REQUEST_URI $request_uri;
		fastcgi_param DOCUMENT_URI $document_uri;
		fastcgi_param DOCUMENT_ROOT /home/gastronomundo/public_html;
		fastcgi_param SERVER_PROTOCOL $server_protocol;
		fastcgi_param REMOTE_ADDR $remote_addr;
		fastcgi_param REMOTE_PORT $remote_port;
		fastcgi_param SERVER_ADDR $server_addr;
		fastcgi_param SERVER_PORT $server_port;
		fastcgi_param SERVER_NAME $server_name;
		fastcgi_param PATH_INFO $fastcgi_path_info;
		fastcgi_param HTTPS $https;
		location ~ \.php(/|$) {
			try_files $uri $fastcgi_script_name =404;
			fastcgi_pass unix:/var/php-nginx/1608739385441220.sock/socket;
		}
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		listen 51.210.241.194:443 ssl;
		ssl_certificate /home/gastronomundo/domains/man.gastronomundo.com/ssl.cert;
		ssl_certificate_key /home/gastronomundo/domains/man.gastronomundo.com/ssl.key;
	}
**man.gastronomundo.com_error_log**
2020/12/24 08:50:09 [error] 451291#0: *284 open() "/home/gastronomundo/public_html/robots.txt" failed (2: No such file or directory), client: 66.249.64.152, server: man.gastronomundo.com, request: "GET /robots.txt HTTP/1.1", host: "man.gastronomundo.com"
2020/12/24 08:50:09 [error] 451291#0: *284 open() "/home/gastronomundo/public_html/login" failed (2: No such file or directory), client: 66.249.64.152, server: man.gastronomundo.com, request: "GET /login HTTP/1.1", host: "man.gastronomundo.com"
2020/12/24 08:55:07 [error] 451291#0: *285 open() "/home/gastronomundo/public_html/interno/login" failed (2: No such file or directory), client: 66.249.64.150, server: man.gastronomundo.com, request: "GET /interno/login HTTP/1.1", host: "man.gastronomundo.com", referrer: "https://man.gastronomundo.com/interno/"
2020/12/24 09:11:56 [error] 451291#0: *292 open() "/home/gastronomundo/public_html/interno/login" failed (2: No such file or directory), client: 46.102.164.182, server: man.gastronomundo.com, request: "GET /interno/login HTTP/1.1", host: "man.gastronomundo.com", referrer: "https://man.gastronomundo.com/interno/"
2020/12/24 09:12:16 [error] 451291#0: *292 open() "/home/gastronomundo/public_html/interno/login" failed (2: No such file or directory), client: 46.102.164.182, server: man.gastronomundo.com, request: "GET /interno/login HTTP/1.1", host: "man.gastronomundo.com"

**Any more ideas?**

**Comment by mggRF** [comment]
The problem occurs during redirection to login.
In Admin.js it is indicated
   `let init = checkUsuario (3)`
and subsequently
... ```
if (init === null) {
     return (<Redirect to = {FOLDER + '/ login'} />)
}
```
and in checkUsuario the null is obtained and does

```
if (init === null) {
     window.location.href = FOLDER + '/ login'
     return init;
   }
```
You can see the list of errors that appear in the console, at the address [man.gastronomundo.com/interno](url)

**Comment by mggRF** [comment]
I is all OK; sorry!!!!!!!!
