### ISSUE TITLE
Adding personal .svg Icons from a folder in app.jsx

### ISSUE THREAD

**Issue by bonchevski** [creativetimofficial/material-dashboard-react#15]
Hey, so I am trying to add my own icons to the appRoutes cosnt in app.jsx(in variables) however I can't seem to import these icons in any way. Any suggestions on how to use our own icons?
I have them as files in a folder

**Comment by EINazare** [comment]
Hello @bonchevski and thank you for your interest in our product.
Are you trying to create icons like those from `material-ui-icons` library?
If so, than you need to have your svg icons inside a `.js` file, not saved as `.svg`, and your icons should have a code similar to (and please consider the fact that this is just an example):
```
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _react = require('react');

var _react2 = _interopRequireDefault(_react);

var _pure = require('recompose/pure');

var _pure2 = _interopRequireDefault(_pure);

var _SvgIcon = require('material-ui/SvgIcon');

var _SvgIcon2 = _interopRequireDefault(_SvgIcon);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var SvgIconCustom = global.__MUI_SvgIcon__ || _SvgIcon2.default;

var _ref = _react2.default.createElement('path', { d: 'M22 5.72l-4.6-3.86-1.29 1.53 4.6 3.86L22 5.72zM7.88 3.39L6.6 1.86 2 5.71l1.29 1.53 4.59-3.85zM12.5 8H11v6l4.75 2.85.75-1.23-4-2.37V8zM12 4c-4.97 0-9 4.03-9 9s4.02 9 9 9c4.97 0 9-4.03 9-9s-4.03-9-9-9zm0 16c-3.87 0-7-3.13-7-7s3.13-7 7-7 7 3.13 7 7-3.13 7-7 7z' });

var AccessAlarm = function AccessAlarm(props) {
  return _react2.default.createElement(
    SvgIconCustom,
    props,
    _ref
  );
};

AccessAlarm = (0, _pure2.default)(AccessAlarm);
AccessAlarm.muiName = 'SvgIcon';

exports.default = AccessAlarm;
```
You would need to change `AccessAlarm` to what your svg icon should be named, and i think you would have to change 
```
'path', { d: 'M22 5.72l-4.6-3.86-1.29 1.53 4.6 3.86L22 5.72zM7.88 3.39L6.6 1.86 2 5.71l1.29 1.53 4.59-3.85zM12.5 8H11v6l4.75 2.85.75-1.23-4-2.37V8zM12 4c-4.97 0-9 4.03-9 9s4.02 9 9 9c4.97 0 9-4.03 9-9s-4.03-9-9-9zm0 16c-3.87 0-7-3.13-7-7s3.13-7 7-7 7 3.13 7 7-3.13 7-7 7z' });
```
with your own svg path.
Than i think you could import them the same way we import `material-ui-icons` and then render them like.

Hope that information helps you. Please let us know if we can help you with anything else.

Best,
Manu

**Comment by intelage-steve** [comment]
Hi @EINazare ,
We have single path icons working using this code. Thank you for showing the way!
How would you represent an svg with multiple paths in the code above? 
Example: 
<svg>
     <path d="M24.5491..." transform="translate..." fill="#123456"/>
     <path d="M1.5 5.75..." transform="translate..." fill="#123456"/> 
</svg

**Comment by EINazare** [comment]
Hello @intelage-steve ,

Unfortunately i do not know how you would do that.
I will take a look at this when i'll have some spare time, until than, maybe someone else will come to your help.

Best,
Manu

**Comment by EINazare** [comment]
Hello again, @intelage-steve ,

I figured out, that you can create your own SVG components very easily like this:
```
import React from "react";
import classnames from "classnames";

function MySVG(props){
   return (
      <svg className={classnames([props.className]: props && props.className)}>
           <path d="M24.5491..." transform="translate..." fill="#123456"/>
           <path d="M1.5 5.75..." transform="translate..." fill="#123456"/> 
      </svg>
   );
}

export default MySVG;
```
I know this issue was addressed a long time ago, I forgot about it. Really sorry about this.

Best,
Manu
