### ISSUE TITLE
[Bug] charts data read from api refresh all charts components

### ISSUE THREAD

**Issue by tmac12** [creativetimofficial/material-dashboard-react#150]
### Version
latest
### Reproduction link
https://github.com/tmac12/material-dashboard-react
### Operating System
Windows 10
### Device
Notebook
### Browser & Version
Chrome 87.0.4280.88
### Steps to reproduce
1. Get data from api every 5 seconds
2. When get data it refresh all the charts not only cpu chart
### What is expected?
Refresh charts data only for cpu charts
### What is actually happening?
Refresh all charts

---
### Solution
I've no solution. Can you help me?

**Comment by EINazare** [comment]
Hello there, @tmac12 ,

I think the issue comes from the fact that the timeout function is set inside the `React.useEffect` hook.
What if you would change the code from:
```
  React.useEffect(() => {
    const intervalId = setInterval(() => {
      handleCpuData();
    }, 5000);
    return () => {
      //cleanup when component DidUnmount
      clearInterval(intervalId);
    };
  }, []);
```
To
```
    const intervalId = setInterval(() => {
      handleCpuData();
    }, 5000);
```

Best,
Manu

**Comment by tmac12** [comment]
Hello @EINazare ,
I try also your solution, but the problem persist.
I want to update only the 'Cpu usage' charts component, but I see that it refresh also other charts: 'daily sales','email subscriptions','completed tasks'.
Here is a video of the problem.
![charts](https://user-images.githubusercontent.com/3485027/104228938-d8b5b700-544b-11eb-935c-a8836fe6530a.gif)

Thank you,
Marco

**Comment by sajadevo** [comment]
**Hi there**

We've just updated the product now it has a new look with a flexible strucutre.

**All the best**
**Sajad**
