### ISSUE TITLE
[Bug] Server prefix is being removed and redirecting to /admin/dashboard.

### ISSUE THREAD

**Issue by bandana2** [creativetimofficial/material-dashboard-react#154]
### Version
-
### Reproduction link
https://github.com/creativetimofficial/material-dashboard-react/blob/master/src/index.js
### Operating System
Linux
### Device
Server
### Browser & Version
Chrome
### Steps to reproduce
1. Check this https://github.com/creativetimofficial/material-dashboard-react/blob/master/src/index.js
2. The site should be running from the sub folder like 'https:myserver/designer/extensions/mypoc/index,html'
3. updated "homepage": "." in the package.json, so it generate all the build files relevant to index.html
3. I am generating build and keeping them in the 'mypoc' folder in the server.
4. Application is running fine, but the url it is showing is ''https:myserver/admin/dashboard'
5. Due to this all prefix(/designer/extensions/mypoc/) I am losing in the url, which is causing few file to not access by the application. like images, mainfect.json etc.

### What is expected?
When the redirect happen, it should keep the prefix.

### What is actually happening?
when redirection happen it is removing the prefix in the server

---

**Comment by EINazare** [comment]
Hello there, @bandana2 ,

This is not an issue with our product, but with the way you build your project.
I suggest you put inside package.json the homepage prop with the value: `/designer/extensions/mypoc/` or something similar.
alternatively, if you still believe this issue comes from the redirect, just delete the `Redirect` from `index.js`.

Best,
Manu

**Comment by bandarunagesh** [comment]
Hi @EINazare,

Thank you for your reply.

 it was not working even when we remove redirect as in Admin component the routes are creating and in NavLink they are creating links to that component.

But, after reasearch found that. React Route is redirecing and it is replacing the prefix, if we user HashRouter it is resolving the issue with out any further changese to the code. 

You may close the issue now.

**Comment by EINazare** [comment]
Hello again, @bandarunagesh ,

Sorry, I forgot about the `HashRouter`.
Another way to solve this - NOTE: I haven't yet tested it - would be, after you've made the build folder, duplicate the index.html into a file named 200.html and a file named 404.html, and you should be able to use the `BrowserRouter`.

But note, I haven't yet tested this with React, only with Svelte.

Best,
Manu
