### ISSUE TITLE
[Bug] Broken NPM dependencies

### ISSUE THREAD

**Issue by rstar2** [creativetimofficial/material-dashboard-react#156]
### Version
1.9
### Reproduction link
https://github.com/rstar2/material-dashboard-react
### Operating System
Ubuntu  20.4
### Device
Linux
### Browser & Version
-
### Steps to reproduce
1. Clone the Github repo https://github.com/creativetimofficial/material-dashboard-react.git  (or use the zip from CreativTim)
2, Try "npm install"
### What is expected?
The project to install
### What is actually happening?
zzzz:~/work/react-mui-dashboard$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: @babel/core@7.9.0
npm ERR! node_modules/@babel/core
npm ERR!   @babel/core@"7.9.0" from react-scripts@3.4.1
npm ERR!   node_modules/react-scripts
npm ERR!     react-scripts@"3.4.1" from the root project
npm ERR!   @babel/core@"^7.4.5" from @svgr/webpack@4.3.3
npm ERR!   node_modules/@svgr/webpack
npm ERR!     @svgr/webpack@"4.3.3" from react-scripts@3.4.1
npm ERR!     node_modules/react-scripts
npm ERR!       react-scripts@"3.4.1" from the root project
npm ERR!   9 more (babel-jest, babel-loader, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @babel/core@"^7.13.0" from @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.13.12
npm ERR! node_modules/@babel/preset-env/node_modules/@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining
npm ERR!   @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@"^7.13.12" from @babel/preset-env@7.13.15
npm ERR!   node_modules/@babel/preset-env
npm ERR!     @babel/preset-env@"^7.4.5" from @svgr/webpack@4.3.3
npm ERR!     node_modules/@svgr/webpack
npm ERR!       @svgr/webpack@"4.3.3" from react-scripts@3.4.1
npm ERR!       node_modules/react-scripts
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/rumen/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rumen/.npm/_logs/2021-04-21T20_45_34_275Z-debug.log

---
### Solution
I guess some dependencies versions incapabilities. I have similar results with the React Argon template

**Comment by rstar2** [comment]
Actually a little more search revealed the problem to be in NPM 7+ .
If someone else experience this see https://github.com/facebook/create-react-app/issues/10749
In my case it's easier to install the project with  **yarn install**

**Comment by ryanzhou7** [comment]
I had a similar problem, with node 14 and 16

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @mui/material@5.2.0
npm ERR! Found: @emotion/react@11.4.1
npm ERR! node_modules/@emotion/react
npm ERR!   @emotion/react@"11.4.1" from the root project
npm ERR!   peer @emotion/react@"^11.0.0-rc.0" from @emotion/styled@11.3.0
npm ERR!   node_modules/@emotion/styled
npm ERR!     @emotion/styled@"11.3.0" from the root project
npm ERR!     peerOptional @emotion/styled@"^11.3.0" from @mui/material@5.2.0
npm ERR!     node_modules/@mui/material
npm ERR!       @mui/material@"5.2.0" from the root project
npm ERR!       1 more (@mui/icons-material)
npm ERR!     1 more (@mui/styled-engine)
npm ERR!   1 more (@mui/styled-engine)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @emotion/react@"^11.5.0" from @mui/material@5.2.0
npm ERR! node_modules/@mui/material
npm ERR!   @mui/material@"5.2.0" from the root project
npm ERR!   peer @mui/material@"^5.0.0" from @mui/icons-material@5.2.0
npm ERR!   node_modules/@mui/icons-material
npm ERR!     @mui/icons-material@"5.2.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @emotion/react@11.7.1
npm ERR! node_modules/@emotion/react
npm ERR!   peerOptional @emotion/react@"^11.5.0" from @mui/material@5.2.0
npm ERR!   node_modules/@mui/material
npm ERR!     @mui/material@"5.2.0" from the root project
npm ERR!     peer @mui/material@"^5.0.0" from @mui/icons-material@5.2.0
npm ERR!     node_modules/@mui/icons-material
npm ERR!       @mui/icons-material@"5.2.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

Fixed via installing with yarn [as documented here](https://github.com/creativetimofficial/material-dashboard-react/issues/171#issuecomment-975642521)

**Comment by sajadevo** [comment]
**Hi Developers**

For these sort of issues please use yarn.

**All the best**
**Sajad**
