### ISSUE TITLE
[Bug] package versions are conflicted

### ISSUE THREAD

**Issue by bigen1925** [creativetimofficial/material-dashboard-react#159]
### Version
1.10.1
### Reproduction link
https://github.com/creativetimofficial/material-dashboard-react/releases/tag/1.10.1
### Operating System
MacOS Catalina 10.15.7
### Device
Macbook Pro
### Browser & Version
without browser
### Steps to reproduce
1. clone the repository
2. `npm install`
### What is expected?
Dependencies are successfully installed,
### What is actually happening?
an error bellow occurred

```
$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!   peer react@"^16.8.0 || ^17.0.0" from @material-ui/core@4.11.4
npm ERR!   node_modules/@material-ui/core
npm ERR!     peer @material-ui/core@"^4.0.0" from @material-ui/icons@4.11.2
npm ERR!     node_modules/@material-ui/icons
npm ERR!       @material-ui/icons@"4.11.2" from the root project
npm ERR!     @material-ui/core@"4.11.4" from the root project
npm ERR!   11 more (@material-ui/icons, @material-ui/styles, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.3.0" from react-event-listener@0.6.6
npm ERR! node_modules/react-event-listener
npm ERR!   react-event-listener@"^0.6.0" from react-swipeable-views-utils@0.13.9
npm ERR!   node_modules/react-swipeable-views-utils
npm ERR!     react-swipeable-views-utils@"^0.13.9" from react-swipeable-views@0.13.9
npm ERR!     node_modules/react-swipeable-views
npm ERR!       react-swipeable-views@"0.13.9" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

---
### Solution
An dependency `react-swipeable-views` does not support React (and React-Dom) 17.

So, matriari-dashboard-react also should depend on React 16.4.0.

**Comment by bigen1925** [comment]
Thank you for developing an awesome dashboard template!

I tried to use, and had a problem when installing dependencies.

I downgraded `React` and `React Dom`, then could installed dependencies.

**Comment by EINazare** [comment]
Hello there, @bigen1925 ,

Maybe try using NodeJS LTS version (v14.16.1) with npm v6.14.12. I think this will also solve the issue, without the need to downgrade React version. In our next version, we'll drop the usage of `react-swipeable-views` since Material-UI has done it as well.

**Comment by bigen1925** [comment]
@EINazare 
I tried to use Node 14.16.1 (and npm v6.14.12), then error didn't occurred.
Before then, I used Node 15.7.0.

This is better than downgrading React. :)

Thank you very much!

**Comment by namendez** [comment]
I solved this upgrading react-swipeable-views dependency to 0.14.0, so far it seems to be working OK (not the best solution but downgrading node and npm was not an option).

**Comment by glaucoheitor** [comment]
May I suggest updating this project to depend on 0.14.0 of react-swipeable-views as that project updated/fix their peerDependencies

https://github.com/oliviertassinari/react-swipeable-views/pull/640

**Comment by sajadevo** [comment]
**Hi there**

We've just updated the product now it has a new look with a flexible strucutre.

**All the best**
**Sajad**

**Comment by noamcohen97** [comment]
What about react 18?

**Comment by sajadevo** [comment]
Hey @noamcohen97,

Until now it's not updated to react 18.

Regards,
Sajad
