### ISSUE TITLE
How can i change project direction to RTL?

### ISSUE THREAD

**Issue by moshtaghi** [creativetimofficial/material-dashboard-react#16]
i read [this document](https://material-ui-next.com/guides/right-to-left/#right-to-left), but i don't understand "step 2", which file is custom theme config?

**Comment by mbrookes** [comment]
https://material-ui-next.com/customization/themes/

Do you want to add a link in the RTL guide to that section?

**Comment by EINazare** [comment]
Hello @moshtaghi and @mbrookes ,

This product does not support RTL.
I am going to discuss this with my superior and see if we are going to add RTL or not, probably we are going to add support.
I'll come again here with a response in a few days. 

Best,
Manu

**Comment by moshtaghi** [comment]
hey @EINazare

**Comment by dalwadani** [comment]
hello @moshtaghi ,
Thanks for creating this fork it is working correctly when running locally. However, when I created the production build using "yarn build" it will break. See screenshot:
![screen shot 2018-06-02 at 8 41 24 am](https://user-images.githubusercontent.com/4618082/40871252-e48cf698-6640-11e8-87d7-27f9606197d1.png)

Any ideas?

**Comment by galdanay** [comment]
> Hello @moshtaghi and @mbrookes ,
> 
> This product does not support RTL.
> I am going to discuss this with my superior and see if we are going to add RTL or not, probably we are going to add support.
> I'll come again here with a response in a few days.
> 
> Best,
> Manu


Hi @EINazare any update for the RTL? in the https://demos.creative-tim.com/material-dashboard-react/#/admin/dashboard there is a RTL page.
But is all the component can get "rtlActive" as a props?
For example the Button ?
Thanks , Gal.

**Comment by EINazare** [comment]
Hello there, @galdanay ,

Only the components present in the RTL page are working on RTL.
Buttons usually have the text centered, so either way, RTL, LTR should work fine.

Best,
Manu

**Comment by galdanay** [comment]
@EINazare thanks!
I am trying to support RTL - for example the CustomInput has RTL in the RTL page.
I cant see any information in the documentation page about how to use RTL:
[https://demos.creative-tim.com/material-dashboard-react/#/documentation/](url)
If there will be some simple example for how to set RTL it's will be great.
Thanks, 
Gal.
