### ISSUE TITLE
[Feature Request] Notification alert is not user friendly 

### ISSUE THREAD

**Issue by aqkhana2002** [creativetimofficial/material-dashboard-react#164]
### What is your enhancement?
if i want to call notification from function how i will call existing ? here is example , i have created response interceptor, whenever there is any issue in response it go to that function and from this function i have to show notification alert which is not possible in current design , so i am using https://www.npmjs.com/package/react-toastify which i do not want to use. but this does solve what i need and i want you must have this

**Comment by sajadevo** [comment]
**Hi there**

We've just updated the product now it has a new look with a flexible strucutre.

**All the best**
**Sajad**
