### ISSUE TITLE
[Bug] Save data when switching tabs

### ISSUE THREAD

**Issue by kiruthemes** [creativetimofficial/material-dashboard-react#165]
### Version
latest
### Reproduction link
https://demos.creative-tim.com/material-dashboard-react/?_ga=2.162934463.226425432.1631562653-1386804182.1631104963#/documentation/tabs
### Operating System
Mac OS
### Device
Macbook
### Browser & Version
Chrome
### Steps to reproduce
1. Create tabs as shown in https://demos.creative-tim.com/material-dashboard-react/?_ga=2.162934463.226425432.1631562653-1386804182.1631104963#/documentation/tabs
2. Input data into fields
3. Switch to another tab
4. Come back to previous tab and you will notice all data entered previously is lost.
### What is expected?
I want to retain the data when switching tabs
### What is actually happening?
Data is lost

---
### Solution
I want to implement the solution proposed here https://stackoverflow.com/questions/50871406/react-recreates-my-component-on-each-material-ui-tab-switch

**Comment by kiruthemes** [comment]
Why do you even provide an option to raise issue if you don't bother responding?

**Comment by sajadevo** [comment]
**Hi there**

We've just updated the product now it has a new look with a flexible strucutre.

**All the best**
**Sajad**
