### ISSUE TITLE
[Bug] [Bug] Icon Page - Google refuses to load icon

### ISSUE THREAD

**Issue by zenzjtech** [creativetimofficial/material-dashboard-react#166]
### Version
1.10.0
### Reproduction link
https://demos.creative-tim.com/material-dashboard-react/?&_ga=2.247118468.1475704086.1632817938-29399667.1632276653#/admin/icons
### Operating System
Linux
### Device
 Dell Latitude E7470
### Browser & Version
Google Chrome 92.0.4515.107 (Official Build) (64-bit)
### Steps to reproduce
1. Go to url https://demos.creative-tim.com/material-dashboard-react/?&_ga=2.247118468.1475704086.1632817938-29399667.1632276653#/admin/icons
2. Icons aren't loaded. (page empty of Google icons), Text displayed: "fonts.google.com refused to connect"
### What is expected?
Google Icons are displayed
### What is actually happening?
No Google Icons visible.

---

**Comment by sajadevo** [comment]
**Hi there**

We've just updated the product now it has a new look with a flexible strucutre.

**All the best**
**Sajad**
