### ISSUE TITLE
[Bug] Unable to resolve dependency tree

### ISSUE THREAD

**Issue by snymty** [creativetimofficial/material-dashboard-react#171]
### Version
v1.10.0
### Reproduction link
https://github.com/creativetimofficial/material-dashboard
### Operating System
MacOs
### Device
Mac mini m1
### Browser & Version
Chrone
### Steps to reproduce
npm install in file where all files are unzipped
### What is expected?
To install all packages
### What is actually happening?
@Mac-mini material-kit-pro-react-v1.10.0 % npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: material-kit-pro-react@1.10.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@">= 15.4.1 < 17.0.0-0" from react-animate-on-scroll@2.1.5
npm ERR! node_modules/react-animate-on-scroll
npm ERR!   react-animate-on-scroll@"2.1.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/aljaz/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:

---
### Solution
Fix dependency tree

**Comment by sajadevo** [comment]
**Hi @snymty **
Please use the following method:
1. Download and install yarn globally using npm: **npm i -g yarn**
2. Head over to the product directory and run the following command: **yarn install**

**All the best**
**Sajad**

**Comment by byuilazenbyt** [comment]
I don't like that solution nearly as much because it really makes it hard to use IDE's that optimized around NPM and not yarn. Yes it allows you to get that project started but now you can't really leverage your IDE which slows down production considerably.

**Comment by sajadevo** [comment]
**Hi @byuilazenbyt **

Its only a quick fix for current situation and we are updating our products and for the new updates you can use it with both npm and yarn.

**All the best**
**Sajad**
