### ISSUE TITLE
dashboard is not working for me i'm using nodejs --verion v16.13.1 and npm 8.2.0

### ISSUE THREAD

**Issue by luffy7874** [creativetimofficial/material-dashboard-react#176]
D:\dev\react\material-dashboard-react-main>npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @mui/material@5.2.0
npm ERR! Found: @emotion/react@11.4.1
npm ERR! node_modules/@emotion/react
npm ERR!   @emotion/react@"11.4.1" from the root project
npm ERR!   peer @emotion/react@"^11.0.0-rc.0" from @emotion/styled@11.3.0
npm ERR!   node_modules/@emotion/styled
npm ERR!     @emotion/styled@"11.3.0" from the root project
npm ERR!     peerOptional @emotion/styled@"^11.3.0" from @mui/material@5.2.0
npm ERR!     node_modules/@mui/material
npm ERR!       @mui/material@"5.2.0" from the root project
npm ERR!       1 more (@mui/icons-material)
npm ERR!     1 more (@mui/styled-engine)
npm ERR!   1 more (@mui/styled-engine)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @emotion/react@"^11.5.0" from @mui/material@5.2.0
npm ERR! node_modules/@mui/material
npm ERR!   @mui/material@"5.2.0" from the root project
npm ERR!   peer @mui/material@"^5.0.0" from @mui/icons-material@5.2.0
npm ERR!   node_modules/@mui/icons-material
npm ERR!     @mui/icons-material@"5.2.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @emotion/react@11.7.0
npm ERR! node_modules/@emotion/react
npm ERR!   peerOptional @emotion/react@"^11.5.0" from @mui/material@5.2.0
npm ERR!   node_modules/@mui/material
npm ERR!     @mui/material@"5.2.0" from the root project
npm ERR!     peer @mui/material@"^5.0.0" from @mui/icons-material@5.2.0
npm ERR!     node_modules/@mui/icons-material
npm ERR!       @mui/icons-material@"5.2.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Ideapad\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ideapad\AppData\Local\npm-cache\_logs\2021-12-12T14_14_28_957Z-debug-0.log

**Comment by LeSauvage** [comment]
See [this link](https://github.com/creativetimofficial/material-dashboard-react/issues/171#issuecomment-975642521), must use yarn install, not npm

**Comment by luffy7874** [comment]
I got it thanks buddy :)
