### ISSUE TITLE
Adding Dropdown in sidenav

### ISSUE THREAD

**Issue by Shazil1** [creativetimofficial/material-dashboard-react#177]
I am not able to add drop down to the sidenav. I tried this from the documentation `{
  type: "collapse",
  name: "Dashboards",
  key: "dashboards",
  icon: <Shop size="12px" />,
  collapse: [
    {
      name: "Analytics",
      key: "analytics",
      route: "/dashboards/analytics",
      component: <Analytics />,
    },
    {
      name: "Sales",
      key: "sales",
      route: "/dashboards/sales",
      component: <Sales />,
    },
  ],
}` I am getting the following error: TypeError: Cannot read properties of undefined (reading 'pathname')

**Comment by sajadevo** [comment]
**Hi @Shazil1 **

Thanks for using our product unfortunately the collapse is only available for the PRO version of the product.

**All the best**
**Sajad**
