### ISSUE TITLE
React Hook "useContext" is called conditionally.

### ISSUE THREAD

**Issue by matteocelani** [creativetimofficial/material-dashboard-react#179]
Failed to compile.

src/components/MDPagination/index.js
  Line 17:28:  React Hook "useContext" is called conditionally. React Hooks must be called in the exact same order in every component render  react-hooks/rules-of-hooks

**Comment by hborole** [comment]
I have the same issue.

**Comment by matteocelani** [comment]
Remove conditionally

`const context = useContext(Context);`

**Comment by sajadevo** [comment]
**Hi there**

Thanks for using our product and reporting this issue, we will take care of that on the next update of the product.

**All the best**
**Sajad**
