### ISSUE TITLE
Assign object to a variable before exporting

### ISSUE THREAD

**Issue by matteocelani** [creativetimofficial/material-dashboard-react#180]
You need to assign the object to a variable before exporting it as default.

Compiled with warnings.

src/assets/theme-dark/base/borders.js
  Line 16:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/base/boxShadows.js
  Line 17:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/base/breakpoints.js
  Line 9:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/base/colors.js
  Line 9:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/base/globals.js
  Line 8:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/appBar.js
  Line 3:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/avatar.js
  Line 8:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/breadcrumbs.js
  Line 10:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/button/contained.js
  Line 13:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/button/index.js
  Line 9:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/button/outlined.js
  Line 13:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/button/root.js
  Line 13:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/button/text.js
  Line 13:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/buttonBase.js
  Line 3:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/card/cardContent.js
  Line 6:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/card/cardMedia.js
  Line 11:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/card/index.js
  Line 15:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/container.js
  Line 28:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/dialog/dialogActions.js
  Line 6:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/dialog/dialogContent.js
  Line 16:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/dialog/dialogContentText.js
  Line 13:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/dialog/dialogTitle.js
  Line 11:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/dialog/index.js
  Line 10:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/divider.js
  Line 12:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/form/autocomplete.js
  Line 18:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/form/checkbox.js
  Line 14:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/form/formControlLabel.js
  Line 13:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/form/formLabel.js
  Line 8:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/form/input.js
  Line 15:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/form/inputLabel.js
  Line 10:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/form/inputOutlined.js
  Line 16:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/form/radio.js
  Line 14:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/form/select.js
  Line 11:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/form/switchButton.js
  Line 17:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/form/textField.js
  Line 8:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/icon.js
  Line 6:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/iconButton.js
  Line 8:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/linearProgress.js
  Line 13:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/link.js
  Line 3:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/list/index.js
  Line 3:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/list/listItem.js
  Line 3:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/list/listItemText.js
  Line 3:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/menu/index.js
  Line 17:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/menu/menuItem.js
  Line 16:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/popover.js
  Line 15:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/sidenav.js
  Line 13:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/slider.js
  Line 15:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/stepper/index.js
  Line 16:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/stepper/step.js
  Line 6:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/stepper/stepConnector.js
  Line 10:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/stepper/stepIcon.js
  Line 12:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/stepper/stepLabel.js
  Line 14:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/svgIcon.js
  Line 6:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/table/tableCell.js
  Line 13:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/table/tableContainer.js
  Line 12:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/table/tableHead.js
  Line 11:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/tabs/index.js
  Line 15:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/tabs/tab.js
  Line 15:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme-dark/components/tooltip.js
  Line 18:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/base/borders.js
  Line 17:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/base/boxShadows.js
  Line 17:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/base/breakpoints.js
  Line 9:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/base/colors.js
  Line 9:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/base/globals.js
  Line 8:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/appBar.js
  Line 3:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/avatar.js
  Line 8:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/breadcrumbs.js
  Line 10:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/button/contained.js
  Line 13:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/button/index.js
  Line 9:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/button/outlined.js
  Line 13:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/button/root.js
  Line 13:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/button/text.js
  Line 13:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/buttonBase.js
  Line 3:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/card/cardContent.js
  Line 6:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/card/cardMedia.js
  Line 11:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/card/index.js
  Line 15:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/container.js
  Line 28:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/dialog/dialogActions.js
  Line 6:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/dialog/dialogContent.js
  Line 15:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/dialog/dialogContentText.js
  Line 13:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/dialog/dialogTitle.js
  Line 11:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/dialog/index.js
  Line 10:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/divider.js
  Line 12:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/form/autocomplete.js
  Line 17:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/form/checkbox.js
  Line 14:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/form/formControlLabel.js
  Line 13:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/form/formLabel.js
  Line 8:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/form/input.js
  Line 12:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/form/inputLabel.js
  Line 10:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/form/inputOutlined.js
  Line 15:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/form/radio.js
  Line 14:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/form/select.js
  Line 11:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/form/switchButton.js
  Line 17:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/form/textField.js
  Line 8:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/icon.js
  Line 6:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/iconButton.js
  Line 8:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/linearProgress.js
  Line 13:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/link.js
  Line 3:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/list/index.js
  Line 3:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/list/listItem.js
  Line 3:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/list/listItemText.js
  Line 3:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/menu/index.js
  Line 17:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/menu/menuItem.js
  Line 15:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/popover.js
  Line 15:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/sidenav.js
  Line 13:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/slider.js
  Line 15:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/stepper/index.js
  Line 16:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/stepper/step.js
  Line 6:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/stepper/stepConnector.js
  Line 10:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/stepper/stepIcon.js
  Line 12:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/stepper/stepLabel.js
  Line 14:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/svgIcon.js
  Line 6:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/table/tableCell.js
  Line 13:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/table/tableContainer.js
  Line 12:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/table/tableHead.js
  Line 11:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/tabs/index.js
  Line 15:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/tabs/tab.js
  Line 15:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/assets/theme/components/tooltip.js
  Line 18:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

**Comment by matteocelani** [comment]
Assign const name to each component and then export it.
Example:
```
export default {
  styleOverrides: {
    paper: {
      backgroundColor: transparent.main,
      boxShadow: md,
      padding: pxToRem(8),
      borderRadius: borderRadius.md,
    },
  },
};

```

it becomes

```
const popover = {
  styleOverrides: {
    paper: {
      backgroundColor: transparent.main,
      boxShadow: md,
      padding: pxToRem(8),
      borderRadius: borderRadius.md,
    },
  },
};

export default popover;
```

![Screenshot 2022-02-09 at 22 11 33](https://user-images.githubusercontent.com/26189482/153290775-738e1944-a208-492f-922c-f57778d373d8.png)

A project with 400 warnings is not too nice

**Comment by sajadevo** [comment]
**Hi @matteocelani **

Thanks for using our product, its the first time that we see that someone has this issue since its working fine without assigning it to a variable as well but anyway we will fix this one today within a new update for the product.

Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/FhCJCaHdQa).

All the best,
Sajad
