### ISSUE TITLE
ERROR in Plugin "react" was conflicted between ".eslintrc.json" and "BaseConfig

### ISSUE THREAD

**Issue by victorjoab98** [creativetimofficial/material-dashboard-react#184]
I'm a newbie, help please. Failed to compile, 1 error and 1 warning:

1.
WARNING in ./node_modules/stylis-plugin-rtl/dist/stylis-rtl.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\material-dashboard-react-main\node_modules\stylis-plugin-rtl\src\stylis-rtl.ts' file: Error: ENOENT: no such file or directory, open 'C:\Ematerial-dashboard-react-main\node_modules\stylis-plugin-rtl\src\stylis-rtl.ts'
 @ ./src/App.js 39:0-42 74:22-31
 @ ./src/index.js 22:0-22 28:35-38

2.
ERROR in Plugin "react" was conflicted between ".eslintrc.json" and "BaseConfig » C:\material-dashboard-react-main\node_modules\react-scripts\node_modules\eslint-config-react-app\base.js".

webpack 5.70.0 compiled with 1 error and 1 warning in 70223 ms

**Comment by sajadevo** [comment]
**Hi @victorjoab98**

Thanks for using our product, could you please tell me that you have the yarnrc.yml on the product directory or not?

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**

**Comment by davidleesbir3** [comment]
I ran into the same problem so I did some research myself. The solution suggested in [this post](https://github.com/facebook/create-react-app/issues/10463#issuecomment-813702443) seems to solve it for me.

**Comment by victorjoab98** [comment]
> 
No, I don't have the yarnrc.yml on the product directory and I dont know where it should be.

**Comment by sajadevo** [comment]
**Hi @victorjoab98**

Inside the product root directory please create a file with the following name: .yarnrc.yml and put the following code inside that file: `pnpFallbackMode: all`. Then run the project.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
