### ISSUE TITLE
 https://www.creative-tim.com/new-issue/material-dashboard-react

### ISSUE THREAD

**Issue by ManideepSadhu** [creativetimofficial/material-dashboard-react#185]
Unable to create select option in input field , which is showing wired css

**Comment by sajadevo** [comment]
**Hi @ManideepSadhu**

Could you please tell me how to do that, I need to know how you put them together to find the issue.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
