### ISSUE TITLE
[Bug] Prevent rerendering when using the configurator

### ISSUE THREAD

**Issue by kraussjo** [creativetimofficial/material-dashboard-react#187]
### Version
2.1.0
### Reproduction link
https://demos.creative-tim.com/material-dashboard-react/#/dashboard
### Operating System
Windows 10
### Device
Desktop
### Browser & Version
Chrome latest
### Steps to reproduce
1. Open Developer Tools (with installed react developer tools)
2. Go to Components
3. Click options and mark "Highlight updates when components render
4. Open configurator in the dashboard, change theme or something else or close the configurator
### What is expected?
Only those components should be rendered where necessary
### What is actually happening?
 You will see rerendering of all components, when you click a button or something else in the configurator, or open or close it

---

**Comment by sajadevo** [comment]
**Hi @kraussjo**

Thanks for using our product, as its a large app and if we do the memoization for each part it will make the codebase much bigger and complicated for the users, we let the users to do this based on the projects they're building using our themes or UI Kits.
But if you want I can help you with that on how you can make it more optimized and prevent from unnecessary re-renders.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**

**Comment by kraussjo** [comment]
Hi Sajad, thank you very much for your answer. And thank you for the high quality product!!! It is an immense pleasure to work with it.

It would help me a lot to get a small tip to optimize the behavior. For now, it would be enough to prevent rerendering when opening and closing the configurator. I have built a sorting and filtering into a table and there a rendering is of course very noticeable. 

I am quite a react newbie. I have read a lot about hooks, context, reducer, useMemo or memo, but I still have problems to transfer this into the code. 

I would be very happy about an answer
Jochen

**Comment by sajadevo** [comment]
**Hi @kraussjo**

Sure you can use this snippet as a reference for doing more optimization.
```jsx
{useMemo(() => (
     <Routes>
          {getRoutes(routes)}
          <Route path="*" element={<Navigate to="/dashboard" />} />
     </Routes>
), [])} 
```

You can see the profiler that there are elements with grey color which mean that are not re-rendering when the configurator is opened or closed.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**

**Comment by kraussjo** [comment]
Hi Sajad,

thank you very much for your answer. The result is a bit better, but i still have the problem that my filtered table is re-rendered and therefore all filters and sorts are reset. this happens even when i reduce or enlarge the browser window. I use the context with reducer that comes with the dashboard. I haven't adjusted much else either, just that the table is filled by fetch and is sortable and filterable. 
in the profiler you can see that the rerender is triggered by a change of the context. the rerender of the table is triggered by a props change.

Is there any other tip how i can improve the behavior? 

Thanks alot

![image](https://user-images.githubusercontent.com/38663002/169525947-d5f0ff6e-db81-4f22-a71a-98a404d390c7.png)

![image](https://user-images.githubusercontent.com/38663002/169526009-73eed284-3b54-4653-8fee-cf7c9d485b39.png)

**Comment by kraussjo** [comment]
Hello again, 

the behavior was my mistake. I used the context wrong, that caused the not wanted rerender or comitten of the table. I adjusted the context for my purposes and now it works correctly.

Sstill thanks for everything
