### ISSUE TITLE
Tables do not work properly

### ISSUE THREAD

**Issue by tamothee** [creativetimofficial/material-dashboard-react#190]
![image](https://user-images.githubusercontent.com/107600297/173986335-9cd25068-05a7-4bc0-8d0f-1063bc8930b5.png)

when trying to use mui table, the formatting of the header and body looks like this.

**Comment by SeatSnobAri** [comment]
im having a similar issue here

**Comment by sajadevo** [comment]
Hey there,

To fix this issue just wrap the table component from MUI with a ThemeProvider and this will fix the issue.

Regards,
Sajad
