### ISSUE TITLE
Documentation not accessible

### ISSUE THREAD

**Issue by dkorber** [creativetimofficial/material-dashboard-react#2]
http://md-react.creative-tim.com/documentation is not working for me.

**Comment by EINazare** [comment]
Hello @dkorber ,

Thank you for your notice about this.
The link for our live documentation is [this one right here](https://creativetimofficial.github.io/material-dashboard-react/#/documentation/tutorial) .
Today we are going to make an update to the archive on the creative-tim platform with the correct link.
I'm sorry for this inconvenient.

All the best, 
Manu
