### ISSUE TITLE
SideNav not Working

### ISSUE THREAD

**Issue by rahultat** [creativetimofficial/material-dashboard-react#200]
Hi Team,

I am trying to create a collapsible side nav but it is giving me the below error.

Cannot read properties of undefined (reading 'pathname')

{
  type: "collapse",
  name: "Dashboards",
  key: "dashboards",
  icon: <Shop size="12px" />,
  collapse: [
    {
      name: "Analytics",
      key: "analytics",
      route: "/dashboards/analytics",
      component: <Analytics />,
    },
    {
      name: "Sales",
      key: "sales",
      route: "/dashboards/sales",
      component: <Sales />,
    },
  ],
}

**Comment by sajadevo** [comment]
@rahultat,

Thanks for using our product, but the collapsible sidenav is not available for the free version.

Cheers,
Sajad
