### ISSUE TITLE
When i turn on dark mode and i press on another tab the dark mode will turn of automatically. how i can fix that?

### ISSUE THREAD

**Issue by Cyxumna** [creativetimofficial/material-dashboard-react#207]

**Comment by sajadevo** [comment]
Hey there,

It only happen if you reload the page and to fix that you can use the local storage method and save the dark mode to local storage.

Regards,
Sajad

**Comment by vberick** [comment]
Hi, can you tell me how can I implement the local method! Thanks in advance
