### ISSUE TITLE
[Bug] cannot read pathname of undefined

### ISSUE THREAD

**Issue by Asiya1330** [creativetimofficial/material-dashboard-react#209]
### Version
1
### Reproduction link
https://github.com/Asiya1330/creativeTim
### Operating System
windows
### Device
hp core intel i3
### Browser & Version
chrome & Version 112.0.5615.138 (Official Build) (64-bit)
### Steps to reproduce
const routes = [
  {
    type: "collapse",
    name: "Dashboards",
    key: "dashboards",
    icon: <Icon fontSize="small">dashboard</Icon>,
    collapse: [
      {
        name: "Analytics",
        key: "analytics",
        route: "/dashboards/analytics",
        component: <SolarMonitor />,
      },
    ],
  },
  {

I have added this in my routes.js
but it says, cannot read pathname of undefined.

### What is expected?
show nested routes
### What is actually happening?
throw error

---

**Comment by sajadevo** [comment]
Hey there,

Thanks for using our product, unfortunately nested routes are not available for the free version.

Regards,
Sajad
