### ISSUE TITLE
Getting to work with Webpack

### ISSUE THREAD

**Issue by mpoli** [creativetimofficial/material-dashboard-react#22]
I am fairly new to webpack and react in general, but I am wondering if it is at all possible to get material-dashboard-react (or material-dashboard-pro-react) to work in tandem (or under) a Webpack react project.

I have managed to solve most compilation issues (except for google maps), but yet the generated code is far from what it should be. CSS is obviously incomplete and I suspect the resulting JS files are also incomplete.

Is there  tutorial or some kind of reference implementation for the Demo or Pro version about how to get this sort of deployment to work correctly? I am attaching my present webpack.config.js and package.json for reference.

I intend to buy the Pro version if I am able to fit it in my project, of course.

Thanks.

Configuration files in https://gist.github.com/mpoli/eaa9dd0d9603e0b0a42a26f89e6a7af4

**Comment by abodehq** [comment]
I am really need to fix this please we need help to make this happend .

**Comment by kdclaw3** [comment]
@mpoli @abodehq I've created a boiler plate project off this project at https://github.com/kdclaw3/earth_rocker_project_boilerplate, it uses a babel/webpack to transile and deploy this app. You can clone that project or use take a look at config -> webpack and .bablerc to help you out.
