### ISSUE TITLE
Use individual components?

### ISSUE THREAD

**Issue by idcmp** [creativetimofficial/material-dashboard-react#23]
Hi! I have an existing project, and I'd really just like to cherry pick components from the dashboard to use (specifically the Timeline). Is there a recommended way to do this?

**Comment by EINazare** [comment]
Hello @idcmp ,

And thank you for your interest in using our products.
If you want a component of ours to add it to our project you need to copy it in your project and all its dependencies.
For example, if you want the Timeline component, just copy `src/components/Timeline/Timeline.jsx`, `src/assets/jss/material-dashboard-pro-react/components/timelineStyle.jsx` and you will also need some stuff from `src/assets/jss/material-dashboard-pro-react.jsx`.

Hope that information helps you. Please let us know if we can help you with anything else.

Best,
Manu

**Comment by idcmp** [comment]
Hey Manu! Thanks for this. I'd like to keep them to the side, so I'm guessing that means I need to massage the imports for what I need. If that's not the case let me know.  Otherwise, thanks!

**Comment by montyclt** [comment]
Why not uploading standalone components into npm?

**Comment by EINazare** [comment]
Hello @montyclt ,

That is a great idea, but it is kind of hard to have a dashboard split into multiple components on npm.
On each update of any of our dependencies, we would than have to update each of that component.
It would be a bit hard working on dozens of projects, just to create one product such as this dashboard.
We've already talked about doing something like this, but we need to figure out a way to make it easier for both us and our clients to use the components.

Hope that information helps you. Please let us know if we can help you with anything else.

Best,
Manu

**Comment by montyclt** [comment]
Hello @EINazare,

Thanks for you response.

I'm trying use StatsCard component standalone following the above instructions, but I'm getting error:

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```
```
Check the render method of `StatsCard`.
```

**Comment by Gabb1995** [comment]
I am trying to use all the components in my project, I am new to React.
I have an assets folder with css, jss and js folders.
Then I have webpack building all the js from the js folder into one js file, and all the css required in the js files to one css file.

I copied the components folder and all the assets into my project but when I try to import a component, webpack says Module not found. Any idea how I can fix this or is this related to Webpack not to this project? Thanks.
