### ISSUE TITLE
not able to run template

### ISSUE THREAD

**Issue by vaishnavirasal** [creativetimofficial/material-dashboard-react#24]
hello sir I am not front end developer. i had downloaded your angular bootstrap material template. but when I am trying to use that template in netbeans i am getting error like "InvalidKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key-map-error" what I suppose to do? please help me to solve this problem or tell me how to user your template in netbeans. thank you

**Comment by EINazare** [comment]
Hello @vaishnavirasal ,

Thank you for using our products.
First of all, let me say that this is the wrong github repository.
This is a React template, not an angular one, so i think you can see why this is not the repository where you were supposed to open this issue, right?
Please open this issue on the right repository.
Second, you have a invalid key for your maps.
[This is a link with what you need to do get an API KEY for Google Maps](https://developers.google.com/maps/documentation/javascript/get-api-key). 
After you get your key, you will need to change in your template `YOUR-KEY-HERE` with the key that you'll get at the given link.

Best,
Manu
