### ISSUE TITLE
<CardHeader> cut in top.

### ISSUE THREAD

**Issue by montyclt** [creativetimofficial/material-dashboard-react#26]
Hello, I'm using `<StatsCard>` as [standalone](https://github.com/creativetimofficial/material-dashboard-react/issues/23), and I'm getting the `<CardHeader>` cut in top in Chrome.

![Screenshot](https://i.imgur.com/IGaQCin.png)

**Comment by evanhdc** [comment]
I saw this issue too. I think it's caused by MUI's Card overflow attribute is default to hidden.

I just set overflow to visible in jss to override MUI's default style. Not sure if it's the best way to handle it.

**Comment by EINazare** [comment]
Hello guys,

If you have updated the material-ui library to other version than `material-ui@1.0.0-beta.41`, this king of issues you are going to experience.
Our jss is made for this version of material-ui and not a higher one.
As of 18th this month, material-ui has released it's stable v1.0.0, this week we are going to start the updated on all of our products that uses material-ui to it's stable version.

@evanhdc , yes, that is the only way to make it work.


Best,
Manu

**Comment by montyclt** [comment]
Ok, Thanks you!
