### ISSUE TITLE
Component input

### ISSUE THREAD

**Issue by hayk199519** [creativetimofficial/material-dashboard-react#27]
In input compponent, the  data came with props . How can i set value in input component and how can i take this value against from input.

**Comment by EINazare** [comment]
Hello @hayk199519 ,

If you want to change the data in input, and retrieve that information, you will need to pass in the `inputProps` property, a `onChange` function, that will change the state of your component (will save in the state of the component the information typed).
Here is a tutorial from the authors of the React library with how to deal with this kind of stuff:
[https://reactjs.org/docs/forms.html](https://reactjs.org/docs/forms.html)
Am i making sense?

Best,
Manu

**Comment by Dorothy006** [comment]
<CustomInput
                                        labelText="UserName"
                                        id="usernamelogin"
                                        formControlProps={{
                                        fullWidth: true
                                        }}
                                        
                                        inputProps={{
                                            name="usernamelogin",
                                            value={this.state.usernamelogin},
                                            onChange={this.handleChange}
                                        }}  
                                    />
are you meaning like this? it still not works

**Comment by EINazare** [comment]
Hello there @Dorothy006 ,

Since inputProps is an Object, you can't have equal sign in it:
```
inputProps={{
                                        name:"usernamelogin",
                                        value:{this.state.usernamelogin},
                                        onChange:{this.handleChange}
                                    }}  
```

Best,
Manu

**Comment by Dorothy006** [comment]
Thanks, it should like this:
inputProps={{
                              name:"usernamelogin",
                              value:this.state.usernamelogin,
                              onChange:this.handleChange
                            }}

**Comment by Amberchen8892** [comment]
Does it work? And how do you define function handleChange?
