### ISSUE TITLE
Use ApolloProvider

### ISSUE THREAD

**Issue by SogoGolf** [creativetimofficial/material-dashboard-react#29]
hi there, many thanks for the awesome template has saved us a ton of time.

where would you recommend that we instantiate ApolloProvider and which main element should we "wrap" so we can use Apollo throughout the app/views ?

**Comment by EINazare** [comment]
Hello @SogoGolf ,

To be honest with you, we haven't used ApolloProvider with any of our products, and i do not know what that is, so i can not advise you. 
The only thing i can give you, is this link https://www.apollographql.com/docs/react/ which i've found on the internet. Not sure how helpful this is. 
Maybe the community will come to help you in your need.

Best, Manu.

**Comment by bilguun** [comment]
Wrap the router inside index.js file, so you can use Apollo throughout the app/views.
