### ISSUE TITLE
Drawer backdrop displaying in front of main content

### ISSUE THREAD

**Issue by AlexNeises** [creativetimofficial/material-dashboard-react#3]
I've been trying to figure out why the Drawer component is rendering the backdrop above my main content.
![image](https://user-images.githubusercontent.com/1816254/35873238-c1bffee8-0b2e-11e8-97f5-b06a35e7fbdd.png)

The login screen is unclickable, and I'm not entirely sure why the main content is sitting below the Drawer component.

**Comment by EINazare** [comment]
Hello @AlexNeises ,

Thank you for your interest in our product.
I am not sure what the problem is. To figure this out i would need to see your files / your project. 

Best, Manu.

**Comment by AlexNeises** [comment]
I figured it out, I needed to add a `variant='permanent'` property on the `Drawer` in the `Sidebar.jsx` file.
