### ISSUE TITLE
Roboto Font is not loaded

### ISSUE THREAD

**Issue by PutziSan** [creativetimofficial/material-dashboard-react#31]
See [the documenation-part about the typeface from material-ui](https://material-ui.com/style/typography/#install-with-a-href-https-www-npmjs-com-package-typeface-roboto-npm-a-). It seems that it is not included in this project.

**Comment by EINazare** [comment]
Hello @PutziSan ,

Thank you for your interest in using our product.
It seems that Material-UI has multiple choices of adding Roboto Font to an application.
On this dashboard/app we've decided to go with the [CDN version](https://material-ui.com/style/typography/#roboto-font-cdn) of it.
Are you saying that our app is not using Roboto Font at all?
Do you have issues with the Fonts?
What are is this issue about?

Thank you,
Manu

**Comment by PutziSan** [comment]
![image](https://user-images.githubusercontent.com/13392042/40646270-f7729d5a-6328-11e8-996e-96ac9ffea0fc.png)

the above example is the local version of mine where i added the mentioned CDN-stylesheet-link in `public/index.html`, the lower one is your live preview. The CDN is not loaded in your preview.

**Comment by EINazare** [comment]
Hello @PutziSan ,

Maybe you have a plugin that doesn't let the CDN to be loaded, or something like this?
Because on my machine they look the same, both local and live preview.
<img width="1262" alt="screen shot 2018-05-29 at 3 32 01 pm" src="https://user-images.githubusercontent.com/26245512/40660014-8b918df0-6358-11e8-9d66-55de16b10bfd.png">

Best,
Manu

**Comment by PutziSan** [comment]
It seems one of us is missing something obvious, I'm not sure who right now ;)

I can't find the line of code where you embed the Roboto font via CDN link. Usually it is done [here](https://github.com/creativetimofficial/material-dashboard-react/blob/master/public/index.html), in the head area.
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500">
...
```

If you haven't included it elsewhere, the font won't load. You can still see a correct result if your browser already has the font in cache, for example. But for other users a different font can then be displayed.

**Comment by EINazare** [comment]
Hello again @PutziSan ,

Yes, you are right. We didn't add that line of code in our product.
On our next update we are going to add it.

Best,
Manu
