### ISSUE TITLE
Cropped icon

### ISSUE THREAD

**Issue by wiradikusuma** [creativetimofficial/material-dashboard-react#33]
Upgraded to "@material-ui/core": "^1.2.0":

![screen shot 2018-06-07 at 12 44 09](https://user-images.githubusercontent.com/481995/41078664-9a7a562c-6a50-11e8-8fdf-5ac10e971569.png)

As a matter of fact, simply upgrading from 1.0.0-beta.41 to 1.0.0-beta.42 will produce the UI bug.

**Comment by EINazare** [comment]
Hello @wiradikusuma ,

Thank you for your interest in using our product.
Indeed if you make yourself update to the dependencies, there will most definitely some bugs in our product.
The update for this product is set for next week. If everything goes well, than we are going to meet our deadline (which is Friday next week).

Best,
Manu.

**Comment by Taughran23** [comment]
HI @wiradikusuma, 

I added overflow: visible to the card object in assets/jss/material-dashboard-react.jsx

`const card = {
  display: "inline-block",
  position: "relative",
  width: "100%",
  margin: "25px 0",
  boxShadow: "0 1px 4px 0 rgba(0, 0, 0, 0.14)",
  borderRadius: "3px",
  color: "rgba(0, 0, 0, 0.87)",
  background: "#fff",
    overflow: "visible"
};`

Hope this works for you

**Comment by EINazare** [comment]
Hello guys,

I've made the update, so everything should work just fine now.

Best,
Manu
