### ISSUE TITLE
Table component - specify selected row

### ISSUE THREAD

**Issue by code-by** [creativetimofficial/material-dashboard-react#34]
What prop one need to use to specify selected row?

**Comment by EINazare** [comment]
Hello @code-by ,

Thank you for your interest in using our product.
Can you please be more detailed in your question?
First of all, i would like to know which table are we speaking of (a simple link to the page in question would do the trick).

Best,
Manu

**Comment by code-by** [comment]
```
import Table from 'components/Table/Table';
...
const MyComponent = ({data}) => (
  <Table
    tableData={data}
  />
);
```

**Comment by EINazare** [comment]
Hello again @code-by ,

I just figured out what you were asking.
Unfortunately our demo `Table` is just for rendering data, and not for multiple purpose.
If you want to add more props to it, then you'll have to implement them, our product comes as is.
Or maybe someone from our community will help you with this.

Best,
Manu
