### ISSUE TITLE
How Can I use all this in my new project using create-react-app?

### ISSUE THREAD

**Issue by piyush97** [creativetimofficial/material-dashboard-react#36]
How Can I use all this in my new project using create-react-app?
I want to use the components, How can I import these in another new project?

**Comment by EINazare** [comment]
Hello @piyush97 ,

Thank you for your interest in using our product.
If you want to add components from our project to yours, you need to copy them in your project, and also copy their dependencies (such as their styles and the dependencies from package.json).

Best,
Manu

**Comment by piyush97** [comment]
But even If I'm using Sidebar by importing it, I'm getting an error that ```jss/components/sidebarstyle.jsx``` **not found.**
What to do?

**Comment by EINazare** [comment]
Hello again @piyush97 ,

Well, then it is pretty obvious what you need to do, you need to add `jss/components/sidebarstyle.jsx` in your project.

Best,
Manu

**Comment by piyush97** [comment]
Sorry but even After Importing it, it's showing the same error. That's what the issue is.

**Comment by piyush97** [comment]
I'm using the pro version of this dashboard, But I didn't understand the routes in this project, could you please give me a comprehensive brief about that same?

**Comment by EINazare** [comment]
Hello again @piyush97 ,

We do have a page on our live doc, about this. [Here is a link in our live docs](https://demos.creative-tim.com/material-dashboard-react/#/documentation/routing-system).
Is it helpful? If not, could you detail what you do not understand? 

Best,
Manu

**Comment by phillyfan1138** [comment]
For me I just had to add the [.env](https://github.com/creativetimofficial/material-dashboard-react/blob/master/.env) file to the project.
