### ISSUE TITLE
Notifications.jsx: Calling setState on an unmounted component.

### ISSUE THREAD

**Issue by W1M0R** [creativetimofficial/material-dashboard-react#37]
### Issue

Notifications not cleared between page changes, causing React warnings printed in the console:

> Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
>     in Notifications (created by WithStyles(Notifications))
>     in WithStyles(Notifications) (at notifications.js:8)
>     in NotificationsPage (created by ComponentRenderer)

### Reproduce

1. Navigate to Notifications page.
2. Click on buttons to generate a few notifications.
3. Navigate to Dashboard page. 
4. After a second the warning is displayed.

### Resolution

1. Notifications.jsx: Add `alertTimeout = null` member.
2. Notifications.jsx: Add `clearAlertTimeout` function:

  ```
clearAlertTimeout() {
    if (this.alertTimeout !== null) {
      clearTimeout(this.alertTimeout);
    }
  }
```

3. Notifications.jsx: Add `componentWillUnmount()` function:
  ```
componentWillUnmount() {
    this.clearAlertTimeout();
  }
```

4. Notifications.jsx: Update `showNotification` function:

  ```
showNotification(place) {
    var x = [];
    x[place] = true;
    this.setState(x);
    this.clearAlertTimeout();
    this.alertTimeout = setTimeout(
      function() {
        x[place] = false;
        this.setState(x);
      }.bind(this),
      6000
    );
  }
```

**Comment by EINazare** [comment]
Hello @W1M0R 

Thank you for your interest in using our product.
We are going to address this issue on our next update.

Best,
Manu
