### ISSUE TITLE
Custom input on error missing helper text

### ISSUE THREAD

**Issue by asemoon** [creativetimofficial/material-dashboard-react#43]
When using the CustomInput component defined in CustomInput.jsx I realized that there is no way to set helperText for the text field when there is an error to inform the user. Would it not make more sense to use TextField from material UI  instead of Input to make this component more generic?

**Comment by EINazare** [comment]
Hello @asemoon ,

Thank you for your interest in using our product and sorry for this late response (i've been on a small vacation - next week i also be on vacation).
We are going to take a look at this for our next update.

Best,
Manu

**Comment by EINazare** [comment]
Hello @asemoon ,

I am doing the update for this product and just realized that the helper text is not implemented in our free product, it is only a PRO feature, so we are going to leave this to our customers to decide if they are going to add it or not for the free version, but is going to be present in our PRO version.

Best,
Manu
