### ISSUE TITLE
Does not render in Internet Explorer 11

### ISSUE THREAD

**Issue by pskorupinski** [creativetimofficial/material-dashboard-react#44]
Hello there,

Is there some particular reason why Material Dashboard React does not render in Internet Explorer 11 and just gives info that JavaScript needs to be enabled - even if IT IS enabled?

Thank you,
Pawel

**Comment by EINazare** [comment]
Hello @pskorupinski ,

Thank you for your interest in using our product.
As of moment i am on a small vacation (this week until Saturday) when i'll get home, i'll see if on my PC - Windows - IE 11 the dashboard works. Meanwhile i will ask a friend to take a look at this and maybe he will be able to help you.

Best,
Manu

**Comment by pskorupinski** [comment]
Hi @EINazare - some update on this?
I have noticed that https://demos.creative-tim.com/material-dashboard-pro-react/#/dashboard loads in IE but https://demos.creative-tim.com/material-dashboard-react/#/dashboard does not.

I have my project based on material-dashboard-pro-react but the behaviour is the same as of non-pro version (does not render). Any idea?
