### ISSUE TITLE
[Enhancement] Add card action props to card header

### ISSUE THREAD

**Issue by victorsilent** [creativetimofficial/material-dashboard-react#46]
You have a CardHeader component that allow a lot of things, but, sometimes I want to add an action at top of card, like a button or iconbutton, currently to do this I need to create a div and use flexbox to set icon on right side and text to left side.

The material-ui lib has that feature at their Card
Code sandbox example: https://codesandbox.io/s/jvm7xqr595

Could you add that on CardHeader component?

**Comment by EINazare** [comment]
Hello @victorsilent ,

Thank you for your interest in using our product and for this feedback.
Unfortunately as of moment we do not intend to add this to this dashboard, and this has to do with the fact that for the paid version of this product, we also offer some PSD or Sketch files, and in those, the feature does not appear.
I will put the tag "enhancement" to your issue, and if the board decides to accept this in all of our products, than it will be added.

Best,
Manu

**Comment by victorsilent** [comment]
Sorry, I submited that issue at wrong repo, my intention was to add at "material-dashboard-pro-react" :p
But thank you for your response!

**Comment by EINazare** [comment]
Hello again @victorsilent ,

Did you had the wrong link for the issues?

Best,
Manu

**Comment by victorsilent** [comment]
No, I just create here and forgot to create at "material-dashboard-pro-react" repository. But you have been solved :p
