### ISSUE TITLE
Is it possible to add eslint and prettier ?

### ISSUE THREAD

**Issue by Lmzd** [creativetimofficial/material-dashboard-react#47]
I think it could be a great update, for the structure and the scalability of this open project :)

**Comment by EINazare** [comment]
Hello @Lmzd ,

And thank you for your interest in using our product.
Could you please show us how we should add eslint or prettier?
Before we've launched this product we've used prettier-cli, so it should have the prettier format.

Best,
Manu

**Comment by Lmzd** [comment]
nice cause I tried to put eslint with airbnb recommanded and it was one most brainfuck things of last month :) 
so if you say i can running lint ci/cd test with only prettier it's also great 👍

**Comment by kdclaw3** [comment]
@Lmzd @EINazare I forked and have created a pull request #50 with eslint & prettier that match the current styling rules

**Comment by EINazare** [comment]
Hello @kdclaw3 ,

Thank you for your pull request, i am going to accept it on our next update, hope this is ok with you.

Best,
Manu

**Comment by kdclaw3** [comment]
@Lmzd I updated my fork https://github.com/kdclaw3/material-dashboard-react with a better eslint/prettier implementation it now uses:

- "eslint:recommended",
- "plugin:react/recommended",
- "plugin:prettier/recommended"

**Comment by ikowadavies** [comment]
For those using WebStorm, this solution https://www.jetbrains.com/help/webstorm/prettier.html#ws_prettier_install worked for me.
