### ISSUE TITLE
How to integrate into existing project--relative paths etc

### ISSUE THREAD

**Issue by nolandg** [creativetimofficial/material-dashboard-react#52]
I'm testing out this version before hopefully buying the paid one. I can't see a quick easy way to integrate it into an existing project though. For maintainability, portability, updates, etc, I don't want to mix your components with mine and I need to be able to put your `src` folder anywhere in my tree. It seems like every instance of something like:
````
import buttonStyle from "assets/jss/material-dashboard-react/components/buttonStyle.jsx";

````
breaks webpack because the paths aren't relative.

How are people integrating this with an existing project? Am I missing something? I don't want to structure my app like yours, I don't want your router, etc. I just want the components and layouts.

Thanks!

**Comment by nolandg** [comment]
Modifying env variables etc is not an option. I'm looking for a MUI theme, not an app framework.

**Comment by nolandg** [comment]
Ideally, do you have this as an npm package so one could just import all the components and make MUI a peer dep?

**Comment by EINazare** [comment]
Hello @nolandg ,

As of moment the dashboard is on npmjs, but it is not configured to work as a npm package.
One of our clients made a pull request  (which we are not allowed yet to accept it)  for another product, which is based on this one, on how to make our product work as a npm package.
Please read the following creativetimofficial/material-kit-react#18
Hope that information helps you. Please let us know if we can help you with anything else.

Best,
Manu

**Comment by nolandg** [comment]
Does the paid version have the same problems? Do I get the source with the paid developer version so that I can make a library that can be used in projects and updated properly?

**Comment by EINazare** [comment]
Hello @nolandg ,

Since the pro version, is paid / with money we do not keep it on npm.
As of moment we are testing on how we can add our paid products on npm.
You cannot use our paid version and put it on npm (since it is paid / it is not open source).

Best,
Manu
