### ISSUE TITLE
Where's the entering point of this project?

### ISSUE THREAD

**Issue by MLNC** [creativetimofficial/material-dashboard-react#55]
Hi I am pretty new with the web development. 
I'm wondering why you have "main": "index.js" in your packge.json file while you don't have any index.js under the root directory. 
It seems like the entering point of this project is public/index.js
Can anyone help?

**Comment by EINazare** [comment]
Hello @MLNC ,

And thank you for your interest in using our product.
I think you are right, the entering point would be public/index.html, but that thing in package.json for us is just a formality, it doesn't do anything.

Best,
Manu

**Comment by MLNC** [comment]
Thanks for the answer @EINazare!
But here comes an other question, I use `npm start` to start the project on my machine and everything looks fine, which means public/index.html is served by npm. How did npm knows the entering point is actually public/index.html instead of index.html under the root which does not exist?

**Comment by EINazare** [comment]
Hello again @MLNC ,

I did not ask myself this question when i started to work with react.
I do think that this comes from create-react-app (actually react-scripts that comes with create-react-app), in the start script (start-js).
But i can't be sure without further investigation.
Maybe the official react page can help you with this question?
If not, i'll do some research.

Best,
Manu

**Comment by MLNC** [comment]
Thanks again @EINazare!
I will do some investigation. 

Best,
Yian
