### ISSUE TITLE
@material-ui/core not a peer dependency

### ISSUE THREAD

**Issue by jasontrigg0** [creativetimofficial/material-dashboard-react#59]
Hi, 

@material-ui/core isn't set as a peer dependency, which (I think) is causing me the first issue here: https://material-ui.com/getting-started/faq/
"You accidentally bundle two versions of Material-UI. You might have a dependency not correctly setting Material-UI as a peer dependency."

This might be able to help with:
#28 #17

**Comment by EINazare** [comment]
Hello @jasontrigg0 ,

Thank you for pointing this out.
I am not that familiar with what peerDependencies does, but i will take a look on the official npm.js docs and see how we can improve our package.json.

Best,
Manu

**Comment by kopax** [comment]
was this fixed?

**Comment by EINazare** [comment]
Hello there, @kopax ,

Not at the moment, no.

Best,
Manu
