### ISSUE TITLE
How can i add new fonts to the project 

### ISSUE THREAD

**Issue by omidgharib** [creativetimofficial/material-dashboard-react#6]
I add @font-face into material-dashboard-react.css but after compiling my urls changed to sth else what should i do?

**Comment by EINazare** [comment]
Hello @omidgharib ,

Thank you for your interest in our product.
I don't see how the url could change as a cause of adding a new font.
Could you please give me your project to see what the problem is? My email is manu@creative-tim.com, or you could add me to your github repo.

Best,
Manu
