### ISSUE TITLE
Need to use AutoComplete and cannot make label to float 

### ISSUE THREAD

**Issue by mspclaims** [creativetimofficial/material-dashboard-react#60]
I'm trying to build web app using material-dashboard-react and I need to use autocomplete .. It turns out MUI v2 does not have AutoComplete and docs suggest using altermatives. react-select has all functionality I need - but I cannot figure out how to make it look similarly to other controls - specifically how to make floating label to float away when user starts typing or click on dropdown.

What I did:

- created a component (IntegratedSelect) that uses react-select from https://github.com/mui-org/material-ui/blob/master/docs/src/pages/demos/autocomplete/IntegrationReactSelect.js
- cloned https://github.com/creativetimofficial/material-dashboard-react/blob/master/src/components/CustomInput/CustomInput.jsx into CustomAutocomplete.jsx and replaced Input with IntegratedSelect
 - modified code to pass id to IntegratedSelect and set that id to Select control

.. and tried a lot of different other approaches (setting refs, using FloatingLabel from @material/react-floating-label etc).. with no luck.

Can you please advise how can I trigger float on the label, or otherwise hookup react-select control with floating label? Any help will be appreciated!

Regards, 
VB

**Comment by EINazare** [comment]
Hello @mspclaims ,

And thank you for your interest in using our product.
Since this feature is available in our [PRO paid](https://www.creative-tim.com/product/material-dashboard-pro-react) version of this product, we suggest you take that product instead.

Best,
Manu

**Comment by mspclaims** [comment]
Thanks for reply! Can you please point me to where I can find list of all additional features available in PRO version? All I see is 'Live Preview' but it's very limited.. 
Does PRO version have AutoComplete? If it does - does it support pagination or infinite scrolling?

**Comment by EINazare** [comment]
Hello again @mspclaims ,

No, we do not have AutoComplete in none of our products.
Although i do not think it is very hard to take the styles from the Select and put them to an [AutoComplete](https://material-ui.com/demos/autocomplete/#autocomplete).
We do have a pagination component
- [https://demos.creative-tim.com/material-dashboard-pro-react/#/components/buttons](https://demos.creative-tim.com/material-dashboard-pro-react/#/components/buttons)
- [https://demos.creative-tim.com/material-dashboard-pro-react/#/documentation/pagination](https://demos.creative-tim.com/material-dashboard-pro-react/#/documentation/pagination)
But please note that this is just Front-End, and not Back-End - you need to add your backend how you want it.

Hope this information helps you.

Best,
Manu

**Comment by mspclaims** [comment]
Thanks for an explanation. 
Can you please clarify what you meant when you said that "this feature is available in our PRO paid version of this product" when I asked for floating label for AutoComplete component if you don't have AutoComplete component at all? What feature is available?
... and you did not reply where I can find list of all additional features available in PRO version...

**Comment by EINazare** [comment]
Hello again @mspclaims ,

```
Can you please clarify what you meant when you said that "this feature is available in our PRO paid version of this product" when I asked for floating label for AutoComplete component if you don't have AutoComplete component at all?
```
My mistake.
We do not have AutoComplete in these two products.
I thought you wanted the Select component.

```
... and you did not reply where I can find list of all additional features available in PRO version...
```
Once again, my mistake, i thought that by giving you the link to our documentation (this one here: [https://demos.creative-tim.com/material-dashboard-pro-react/#/documentation/pagination](https://demos.creative-tim.com/material-dashboard-pro-react/#/documentation/pagination)) you will be able to figure out that the sidebar - left menu, from our documentation presents all the components that we have implemented in our product.


So, to start over again.
Here is a link to our documentation: [https://demos.creative-tim.com/material-dashboard-pro-react/#/documentation/tutorial](https://demos.creative-tim.com/material-dashboard-pro-react/#/documentation/tutorial)
You will find all the components in the left side menu.

Hope that information helps you. Please let us know if we can help you with anything else.

Best,
Manu
