### ISSUE TITLE
Gitter link is DEAD

### ISSUE THREAD

**Issue by manishsaraan** [creativetimofficial/material-dashboard-react#62]
Gitter link in reamde is DEAD.
Ref: https://gitter.im/creative-tim/material-dashboard-react?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by EINazare** [comment]
Hello there @manishsaraan ,

Thank you for pointing this out.
The link was actually this one: [https://gitter.im/creative-tim/material-dashboard?utm_source=share-link&utm_medium=link&utm_campaign=share-link](https://gitter.im/creative-tim/material-dashboard?utm_source=share-link&utm_medium=link&utm_campaign=share-link)

We are going to change it in our next update.

Best,
Manu

**Comment by manishsaraan** [comment]
I will submit a pr for this fix.
