### ISSUE TITLE
Unable to use npm package in Meteor project.

### ISSUE THREAD

**Issue by vrondla** [creativetimofficial/material-dashboard-react#64]
# Prerequisites
Please answer the following questions for yourself before submitting an issue.

- [Yes ] I am running the latest version
- [Yes] I checked the documentation and found no answer
- [Yes] I checked to make sure that this issue has not already been filed
- [Yes ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Expected to be able to import and render the Dashboard page. 

# Current Behavior

Seeing the following error in console:

**Unable to resolve some modules:

 "@material-dashboard-react/layouts/Dashboard/Dashboard.jsx" in /Users/DONIV/Documents/workspace/GitHub/TESTPROJECT/imports/ui/routes/index.jsx (web.browser.legacy)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save @material-dashboard-react/layouts**

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create a sample Meteor project. 
2. Install the package using `npm i material-dashboard-react` into meteor project
3. Try to import the components like `import Dashboard from "@material-dashboard-react/layouts/Dashboard/Dashboard.jsx";`.

## Context

I am just trying to use the module in my latest Meteor 1.7.x projects.

* Device: Macbook Pro
* Operating System: Mac OS
* Browser and Version: Chrome

**Comment by EINazare** [comment]
Hello there @vrondla ,

Thank you for your interest in using our product.
Your import should be `import Dashboard from 'material-dashboard-react/dist/layouts/Dashboard/Dashboard.js';`.
Our product was not designed for npm and there are still some problems.
Right now we are focusing on updating our products to the newer version of Material-UI, and can't really attend to this issue.
When I put it on npmjs, I've only tested it for importing components and they work fine. I didn't realize that our users would like to use our layouts as well.

Best,
Manu

**Comment by tgmarinho** [comment]
Hi @EINazare I have the same issue, is there a way when I do `npm i material-dashboard-react` only come the source font inside of dist instead of getting all files of development?

**Comment by EINazare** [comment]
Hello there @tgmarinho ,

Thank you for your interest in working with our products.
Unfortunately, the answer is no.

Best,
Manu
