### ISSUE TITLE
Impossible to change colors

### ISSUE THREAD

**Issue by vbartusevicius** [creativetimofficial/material-dashboard-react#66]
First of all - thank you for great job you did. The dashboard looks really great, but after we got used to it, we bumped into major issues:

At first it seems that primary color is defined in `material-dashboard-react.jsx` with name `primaryColor`. That looked great, but:
* just below there is `primaryBoxShadow` which uses hard-coded RGB values of `primaryColor`.
* same thing with `primaryCardHeader` - hardcoded RGB
* `buttonStyle.jsx` - `buttonStyle.primary` uses hardcoded RGB for boxShadow.

Same applies for all colors.
It is practically a rewrite for someone willing to use different color palette and total mess is guaranteed when one would like to update package.

In my opinion best approach would be to use custom Material-ui theme as this is how they suggest to customize components. If that's not possible I suggest to use some color manipulation package, like https://www.npmjs.com/package/color:

```
const colorPrimary = Color('#ff9800');
const primaryBoxShadow = {
    boxShadow:
        `0 12px 20px -10px ${colorPrimary.alpha(0.28).rgb().string()}, 0 4px 20px 0px rgba(0, 0, 0, 0.12), 0 7px 8px -5px ${colorPrimary.alpha(0.2).rgb().string()}`
};
```

Sorry for criticism, but this is a main issue we decided to abandon further integration of this nice dashboard.

**Comment by EINazare** [comment]
Hello @vbartusevicius ,

I am sorry to hear this.
At the moment we do not have time to refactor all of our code.
When we will have some spare time we will see how we can make our code more variable friendly than it is now.

Best,
Manu

**Comment by kaos** [comment]
This is one of my main concerns as well. That the styling doesn't use the features present in material ui (theme-ing) is a big surprise, and makes it hard to get the look-and-feel consistent when using standard material ui components along with those from this kit.

The second issue being that we can't install and use these components as a normal library dependency in a sensible way.

Love the stuff you've done with it, so if those two are fixed, it'll be a really nice addition to the material ui experience.

**Comment by EINazare** [comment]
Hello there @kaos ,

Thank you for your interest in working with our products, and sorry for this issue.
At the moment we are stuck on some other projects, and we do not have the time needed to make major changes to these products (speaking here about the Material React products).

Best,
Manu
