### ISSUE TITLE
JSON syntax error in .babelrc

### ISSUE THREAD

**Issue by ascooper57** [creativetimofficial/material-dashboard-react#67]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Y] I am running the latest version 1.5.0
- [Y ] I checked the documentation and found no answer
- [Y ] I checked to make sure that this issue has not already been filed
- [Y ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

Should not have trailing comma

Fixed version:

=========================================================================
{
  "presets": ["es2015"],
  "plugins": [
    "transform-class-properties",
    "transform-react-jsx",
    "transform-object-rest-spread",
    ["module-resolver", {
      "root": ["./src"]
    }],
    ["import-rename", {"^(.*)\\.jsx$": "$1"}]
  ]
}
==========================================================================

**Comment by EINazare** [comment]
Hello there @ascooper57 ,

Thank you for your interest in using our product, and for showing us this human error.
We are going to change it in our next update - the .babelrc file is just something used by us so that we can create a package out of the product.

Best,
Manu
