### ISSUE TITLE
package.json missing dependency: prop-types

### ISSUE THREAD

**Issue by ascooper57** [creativetimofficial/material-dashboard-react#68]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ 1.5.0] I am running the latest version
- [ Y] I checked the documentation and found no answer
- [Y ] I checked to make sure that this issue has not already been filed
- [ Y] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Dashboard.jsx (and other files) has:
     import PropTypes from "prop-types";
yet module is not in package.json, Its absence creates 45 warnings in JetBrains WebStorm

**Comment by EINazare** [comment]
Hello again @ascooper57 ,

Thank you for showing this issue.
We are going to address this issue on our next update.

Best,
Manu
