### ISSUE TITLE
assets/img and assets/css folders and files missing after npm run build-package

### ISSUE THREAD

**Issue by ascooper57** [creativetimofficial/material-dashboard-react#69]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ 1.5.0] I am running the latest version
- [ Y] I checked the documentation and found no answer
- [ Y] I checked to make sure that this issue has not already been filed
- [ Y] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

Dashboard.js, index.js and UserProfile.js references files in dist/assets/img or css but they these folders are missing:

# Current Behavior

What is the current behavior?

Only the dist/assets/jss folder is present

**Comment by EINazare** [comment]
Hello again @ascooper57 ,

The `build-package` was used by us so that we can create a package out of this product.
Yes, it is strange that it does not output the css files as well.
To solve the issue, replace that script with these two:
```
"build-package-css": "cp src/assets/css/material-dashboard-react.css dist/material-dashboard-react.css",
"build-package": "npm run build-package-css && babel src --out-dir dist"
```

Best,
Manu

**Comment by ndmax** [comment]
Thanks @EINazare for the resolve suggestion.  Unfortunately, after replacing the `build-package` script definition with the two above, I see the same error:

![mui-dash-error](https://user-images.githubusercontent.com/4944626/47256780-40d6e780-d453-11e8-8460-5bf52eea6b61.png)

I'm not sure if it matters, but `./src/assets/css/material-dashboard-react.css` seems to exist.

**Comment by YuhanLee** [comment]
Hello! I was wondering if there is a solution to this issue?

**Comment by EINazare** [comment]
Hello there @YuhanLee ,

Please read my last comment.

Best,
Manu

**Comment by YuhanLee** [comment]
I was wondering where to change those two lines? I inspected the package.json from this library, but those two scripts are present. 
Thank you, 

Yuhan

**Comment by EINazare** [comment]
Hello again @YuhanLee ,

In the "scripts" object inside package.json.

Hope this helps.

Best,
Manu

**Comment by scottsawyer** [comment]
Fixed by using bower

**Comment by oluizcunha** [comment]
> Fixed by using bower

Explain better
