### ISSUE TITLE
How can I integrate material-dashboard-react with laravel preset with react scaffolding ?

### ISSUE THREAD

**Issue by momo-barro** [creativetimofficial/material-dashboard-react#72]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by EINazare** [comment]
Hello there @momo-barro ,

Thank you for your interest in working with our products.
Here are a few tutorials that I've just found on how to use React with Laravel:

- [https://blog.pusher.com/react-laravel-application/](https://blog.pusher.com/react-laravel-application/)
- [https://code.tutsplus.com/tutorials/build-a-react-app-with-laravel-restful-backend-part-1-laravel-5-api--cms-29442](https://code.tutsplus.com/tutorials/build-a-react-app-with-laravel-restful-backend-part-1-laravel-5-api--cms-29442)
- [https://www.youtube.com/watch?v=P8Ic_kTv3Xg](https://www.youtube.com/watch?v=P8Ic_kTv3Xg)

Hope this information helps you. 

Best,
Manu

**Comment by momo-barro** [comment]
Hello @EINazare thanks for your answer.

My problem is not how to build a restful react / laravel app but how to integrate your template in a react / laravel environment. When I execute the "npm i material-dashboard-react" command, everything about your template is installed in the "node modules", with the "material-dashboard-react" as a dev dependency in the "package.json". Since react components should be in "ressources/js/components" how can I display the dashboard if there is no component in that folder but in the "node modules" ?

Best,
Momo

**Comment by EINazare** [comment]
Hello there @momo-barro ,

I am not an expert in Laravel, and none of my colleagues are - since we are a front-end company, we kind of do not know that much back-end, and I really can not assist you in this.
I will leave the issue opened, and maybe someone with Laravel and React knowledge will come to your help.
A small guidance that I can give, is to simply copy and paste our components into `ressources/js/components`.

Best,
Manu

**Comment by anghelalexandra** [comment]
@momo-barro I haven't tested this, but the way I would do it is to create a build / production version of the application by running `npm build`. This command should create a `build` folder with minified .js and .css files and other static resources that you can then copy in the `resources` folder from Laravel. You shouldn't need other React files besides the build.

**Comment by aakhan89** [comment]
> @anghelalexandra thanks for your help ! I'm gonna try that.

Hey @momo-barro , Have you tried ?

**Comment by aakhan89** [comment]
@anghelalexandra 
Can you please look into this and provide the better solution

**Comment by EINazare** [comment]
Hello there @aakhan89 ,

Thank you for your interest in working with our product.
As I've stated in my last comment on this thread I haven't worked with Laravel and do not know what working with Laravel and React requires, I am betting that you know more about this than me.
If it were up to me, I would just copy and paste the components that I needed inside the `ressources/js/components` folder.

Best,
Manu

**Comment by momo-barro** [comment]
hey @aakhan89 keep me updated to buddy.  :) I think the biggest challenge of @EINazare approche is to get all the template dependencies all in place without having in your google console this nasty error; https://stackoverflow.com/questions/52988076/react-laravel-uncaught-error-target-container-is-not-a-dom-element/
