### ISSUE TITLE
How I can add login page? I added a new page but routes doesn't work. want some help in add routes which wont be part of sidebar. I want to see login page first and after login dashboard should be seen.

### ISSUE THREAD

**Issue by Tejalsjsu** [creativetimofficial/material-dashboard-react#74]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by EINazare** [comment]
Hello there @Tejalsjsu ,

Thank you for your interest in working with our product.
We actually have Login Page inside the PRO version: https://www.creative-tim.com/product/material-dashboard-pro-react
Feel free to get that product instead.

Best,
Manu
