### ISSUE TITLE
Icons don't scroll in filter menu in the Icons page

### ISSUE THREAD

**Issue by abumalick** [creativetimofficial/material-dashboard-react#75]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
in https://demos.creative-tim.com/material-dashboard-react/#/icons when scrolling the left menu, icons should scroll with content

# Current Behavior
icons are fixed and don't scroll with content
![image](https://user-images.githubusercontent.com/8377185/49098541-05f07c80-f267-11e8-8adf-fd650a480f46.png)

# Failure Information (for bugs)

## Steps to Reproduce

1. got to https://demos.creative-tim.com/material-dashboard-react/#/icons
2. make the filter menu scroll
3. you get it...

## Context

* Device: macbook pro
* Operating System: macOS
* Browser and Version: chrome last version

**Comment by EINazare** [comment]
Hello there @abumalick ,

Thank you for your interest in working with our products and for telling us about this issue.
Unfortunately, that is an iframe, and the issue comes from material-io, and not from us.

Best,
Manu
