### ISSUE TITLE
How do I get the files to make my React Table look like your demo DataTables.net?

### ISSUE THREAD

**Issue by ascooper57** [creativetimofficial/material-dashboard-react#76]
alanooper DOWNLOADED 1 day ago
I have the material-dashboard-pro 1.4.0 version. I am using the React Table in src/views/Tables/ReactTables.jsx. How do I get the files to make my React Table look like your demo
![datatables net](https://user-images.githubusercontent.com/5903533/49660446-792e8700-f9fb-11e8-8f79-20043dedef3c.png)
![reacttables](https://user-images.githubusercontent.com/5903533/49660450-7c297780-f9fb-11e8-8445-cb0b7d979ab0.png)

: https://demos.creative-tim.com/material-dashboard-pro/examples/tables/datatables.net.html Alan S. Cooper 

!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

einazare OWNER
Hello again @alanooper . Please open a GitHub issue here: https://github.com/creativetimofficial/material-dashboard-react/issues . I do not understand your issue. Best, Manu.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X ] I am running the latest version Pro 1.4.0
- [ X] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed
- [ X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

See attachment  DataTables.net.png

Please describe the behavior you are expecting

Better sorting GUI, Page Navigation on bottom right of screen

# Current Behavior

What is the current behavior?

See attachment: ReactTables.png

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by EINazare** [comment]
Hello there @ascooper57 ,

Thank you for your interest in working with our product.
Unfortunately, since the DataTables.net and React-table are two different libraries, this cannot be achieved.

Best,
Manu
