### ISSUE TITLE
Integrate existing login page into the dashboard template

### ISSUE THREAD

**Issue by ZaidOm** [creativetimofficial/material-dashboard-react#77]
Hey I need some help, I have a LoginPage that I would like to add onto the dashboard. However, I'm trying to make it the initial page. Do you know how I could make it the initial page and make it so the 'sign in' button on the login page successfully routes to the dashboard? Thank You!

**Comment by EINazare** [comment]
Hello there @ZaidOm ,

Thank you for your interest in working with our product.
Please take a look at our live docs: https://demos.creative-tim.com/material-dashboard-react/#/documentation/routing-system

Hope this information will help you.

Best,
Manu
