### ISSUE TITLE
No starter server included for built project

### ISSUE THREAD

**Issue by aeroxy** [creativetimofficial/material-dashboard-react#8]
I wrote a simple Node.js server to serve files from build folder, yet I open up an empty page. I think a simple server should be included so people have some basic idea how to get started with the built files.

**Comment by EINazare** [comment]
Hello @aeroxy ,

Thank you for your interest in our product.
Not sure why you would need to create a server from the build folder when you have `npm start`, which basically does that.
We haven't done this before, but we are going to take a look on how to serve the build folder and add it in our documentation.

Best,
Manu

**Comment by aeroxy** [comment]
Oh does npm start serve from build folder? I was under the impression it is serving from src.

**Comment by EINazare** [comment]
As of the official documentation i believe that `npm start` is creating a server. [Here is a link with the official documentation](https://reactjs.org/blog/2016/07/22/create-apps-with-no-configuration.html#starting-the-server).

Best,
Manu
