### ISSUE TITLE
build can't find files

### ISSUE THREAD

**Issue by andrewgbliss** [creativetimofficial/material-dashboard-react#82]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

When I run npm run build that it would build a production ready app

# Current Behavior

I ran npm run build and when I run the files from the build folder it can't find any files. I opened up the index.html and it seems to prefix everything with /material-dashboard-react in every url.
If I remove those url prefixes everything works fine. Every react app works fine in the build process I have worked with.

**Comment by EINazare** [comment]
Hello there @andrewgbliss ,

Thank you for your interest in working with our products.
To solve this, please go inside package.json and delete the homepage prop:
```
  "homepage": "https://creativetimofficial.github.io/material-dashboard-react/#/dashboard",
```
This should do the trick.

Waiting for your response.

Best,
Manu

**Comment by andrewgbliss** [comment]
@EINazare Yes this worked for me. Thanks.
