### ISSUE TITLE
Routing System documentation page error

### ISSUE THREAD

**Issue by arealdeadone** [creativetimofficial/material-dashboard-react#85]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
Documentation of Routing System

# Current Behavior
When I try to access the documentation for the _**Routing System**_ the page is blank and the chrome javascript console shows an error.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Visit [Routing System Documentation](https://demos.creative-tim.com/material-dashboard-react/#/documentation/routing-system)
2. The Page is blank

![screen shot 2019-02-23 at 10 28 43 am](https://user-images.githubusercontent.com/13249112/53281909-39538200-3756-11e9-96c0-179d29af7b3f.png)

**Comment by EINazare** [comment]
Hello there @arealdeadone ,

Thank you for telling us about this issue.
I've just solved it.
Please refresh the page, or change the browser that you are using.

Best,
Manu
