### ISSUE TITLE
running a fresh build gives Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by codecraf8** [creativetimofficial/material-dashboard-react#86]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Yes ] I am running the latest version
- [ Yes ] I checked the documentation and found no answer
- [ Yes ] I checked to make sure that this issue has not already been filed
- [ Yes ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

```
git clone git@github.com:creativetimofficial/material-dashboard-react.git

npm install 

npm run-script build 

npm install -g serve 

serve -s build 


```
Please describe the behaviour you are expecting

Want to see the html being rendered. 

# Current Behavior
<img width="1356" alt="screenshot 2019-03-03 at 9 19 55 am" src="https://user-images.githubusercontent.com/14155171/53690718-0c2a5380-3d96-11e9-949f-1448c7840727.png">

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. clone the repo
2. install packages
3. run a build
4. try to open the built html

**Comment by EINazare** [comment]
Hello there @codecraf8 ,

Thank you for your interest in working with our products.
Go inside package.json and delete the homepage prop.
That'll do the trick.

Best,
Manu
