### ISSUE TITLE
You should not use <Link> outside a <Router>

### ISSUE THREAD

**Issue by justnajm** [creativetimofficial/material-dashboard-react#87]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Demo should run after npm install and npm start

# Current Behavior

Throws this error: "You should not use <Link> outside a <Router>"

# Failure Information (for bugs)

invariant
E:\material-dashboard\node_modules\babel-loader\lib\index.js??ref--6-oneOf-2!E:\material-dashboard\node_modules\invariant\browser.js:34

  31 | } else {
  32 |   var args = [a, b, c, d, e, f];
  33 |   var argIndex = 0;
> 34 |   error = new Error(format.replace(/%s/g, function () {
     | ^  35 |     return args[argIndex++];
  36 |   }));
  37 |   error.name = 'Invariant Violation';

render
E:\material-dashboard\node_modules\babel-loader\lib\index.js??ref--6-oneOf-2!E:\material-dashboard\node_modules\react-router-dom\es\Link.js:121

  118 |   return React.createElement("a", _extends({}, props, {
  119 |     onClick: this.handleClick,
  120 |     href: href,
> 121 |     ref: innerRef
      | ^  122 |   }));
  123 | };
  124 | 
## Steps to Reproduce

1. download dashboard
2. npm install
3. npm run

## Context

Windows 7
NPM 5.6.0
Node 8.11.1
Browser Firefox 65
Terminal Cygwin Bash
Firewall: no firewall
Theme: default
Framework React
IP: private

## Failure Logs

All Files of this repository and npm install dependencies

**Comment by rafull6** [comment]
I have same problem :(

**Comment by rafull6** [comment]
I found a solution. After I updated react-router-dom to version 4.4.0 - problem disappeared.

**Comment by justnajm** [comment]
Thanks @rafull6 

For any beginners like me, do the following:
1. In package.json find this line: "react-router-dom": "4.3.1",
2. Replace it with this line:    "react-router-dom": "4.4.0",
3. npm update
4. npm start

Done ;)

**Comment by EINazare** [comment]
Hello there, guys,

Thank you for your interest in working with our products.
Sorry for the late response, we do not work on weekends.
In our package.json file we only install "react-router-dom". This package auto-installs "react-router". The problem is that is installing the latest version of "react-router", instead of the same version as "react-router-dom", and that is why you are having this error.
Run the following command:
```
npm i -E react-router@4.3.1
```
And this will do the trick.

Best,
Manu
