### ISSUE TITLE
i wanna use of decorators in my project and i configed my babel ,actually i used of some transofrmer but it wasnt work , could ypu please help me ?

### ISSUE THREAD

**Issue by zahrahajilary** [creativetimofficial/material-dashboard-react#88]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by EINazare** [comment]
Hello there @zahrahajilary ,

Thank you for your interest in working with our products.
Is this link helpful to you (Please, read carefully the whole article): https://medium.freecodecamp.org/how-to-use-reactjs-with-webpack-4-babel-7-and-material-design-ff754586f618

Best,
Manu

**Comment by zahrahajilary** [comment]
Thanks , its so helpfull for me
