### ISSUE TITLE
Search component determines positioning of the Headerlinks

### ISSUE THREAD

**Issue by markwemekamp** [creativetimofficial/material-dashboard-react#9]
Hi,
Thanks for the awesome templates.
I was fiddling around with the template and discovered that removing the search components from HeaderLinks.jsx messes up the layout of the headerlinks.

![image](https://user-images.githubusercontent.com/3817270/37842231-dccee968-2ec1-11e8-9b44-5c02c4c3fb24.png)

It appears the CustomInput marginTop class is responsible for the positioning of the entire HeaderLinks section of the template

**Comment by EINazare** [comment]
Hello @markwemekamp ,

Thank you for your interest in using our product and for telling us about this issue.
We are going to solve this problem in our next update, which will be done this week.

Best,
Manu
