### ISSUE TITLE
Compilation error when installing via npm (package is missing files/folders)

### ISSUE THREAD

**Issue by psycr0w13** [creativetimofficial/material-dashboard-react#93]
# Prerequisites
I installed material-dashboard-react with npm i material-dashboard-react like advised in the documentation, but the problem here is that the npm package seems to be missing some folders/files (material-dashboard-react/dist/assets/*). in the assets folder there should be folders like img and css etc. But the only folder I can find in there is jss. This, I think, is the reason for the compilation error. So your npm package is broken and does not work. I simply cant use this package if it doesnt work with npm, because I wont install it manually. Thats a no go. Could you maybe update thje npm package? Or am I missing something here?
Id really like to use this dashboard.

RELATED ISSUE:
https://github.com/creativetimofficial/material-dashboard-react/issues/69

--> I inspected the package.json, but the two lines mentioned by you (to insert) in the other issue are present in the scripts section of the package.json, but this doesnt solve the issue with the package, the folders are still missing!

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
My project should compile with no errors and display a simple card.

# Current Behavior
Compilation error:

Failed to compile.

./node_modules/material-dashboard-react/dist/views/UserProfile/UserProfile.js
Module not found: Can't resolve '../../assets/img/faces/marc.jpg' in '/root/WebstormProjects/carshield/carshield_frontend/node_modules/material-dashboard-react/dist/views/UserProfile'

# Failure Information (for bugs)
As mentioned above.

## Steps to Reproduce

1. install the package via npm
2. use something of the package, I think it wont compile even if you dont use something of the package
3. See the compilation error because of missinf files/folders

Would be great to get help or maybe a fixed npm package :)
Thanks in advance

**Comment by psycr0w13** [comment]
If the npm package doesn't work out of the box, I cant use this dashboard because I have an automatic install and configuration script and there I simply cant use any workarounds. 
Thank you :)

**Comment by EINazare** [comment]
Hello there, @psycr0w13 ,

Thank you for your interest in working with our products.
We'll invest some time in making our products work on npm.
At the moment we have other projects that we are working on and we do not have a fair estimate for this. 

Best,
Manu

**Comment by psycr0w13** [comment]
Thank you for the answer. Ill be back then ;)
Have nice day,
Max
