### ISSUE TITLE
Sharing the components between projects

### ISSUE THREAD

**Issue by yty-agnitio** [creativetimofficial/material-dashboard-react#94]
[ ] I am running the latest version
[x] I checked the documentation and found no answer
[x] I checked to make sure that this issue has not already been filed
[ ] I'm reporting the issue to the correct repository (for multi-repository projects)

Any advice on how to share the components between two (or more) projects ? Should I just copy them manually to each project ? 
Also, when I want to update the components to the latest version, is it safe to just replace the outdated components with the new ones  ?

**Comment by EINazare** [comment]
Hello there, @yty-agnitio ,

Thank you for your interest in working with our products:
> Any advice on how to share the components between two (or more) projects ? Should I just copy them manually to each project ?

Please refer to this GitHub issue: https://github.com/creativetimofficial/ct-material-dashboard-pro-react/issues/50#issuecomment-407030675

> Also, when I want to update the components to the latest version, is it safe to just replace the outdated components with the new ones ?

Yes.

Best,
Manu
