### ISSUE TITLE
i get a white screen after deploy this template

### ISSUE THREAD

**Issue by d1sd41n** [creativetimofficial/material-dashboard-react#97]
First I would like to thank for this template that is very beautiful.

I have a problem with the template, I tried to deploy the template, my project that was made with this template, and then the raw template as it is here in the repository, but with both, when I open them in the browser I get a white screen and I get these errors in the console:

Uncaught SyntaxError: Unexpected token <
main.2720860f.chunk.js:1 Uncaught SyntaxError: Unexpected token <
manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.

![Captura](https://user-images.githubusercontent.com/34890805/64395347-87a7de80-d01f-11e9-9b37-c99f5271c41b.PNG)

here is the deploy of raw template with the error in case anyone wants to look:

https://material-dashboard-react-rddongqii.now.sh

I don't know how to solve this problem, does anyone have any idea what happens and how could it be solved?

**Comment by EINazare** [comment]
Hello there, @d1sd41n ,

Please delete the homepage prop from the package.json.
I have a question, why did you not use our issue template:
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/material-dashboard-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->
```

Best,
Manu

**Comment by d1sd41n** [comment]
I had already solved the problem by replacing the package.json with a completely new one, but thank you very much for responding, I did not know the existence of the issue template so I posted the problem here, but the next one will be there. greetings!

**Comment by tanvirstreame** [comment]
> Hello there, @d1sd41n ,
> 
> Please delete the homepage prop from the package.json.
> I have a question, why did you not use our issue template:
> 
> ```
> 
> 
> 
> ```
> 
> Best,
> Manu

It works
