### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by Pirantul** [creativetimofficial/material-dashboard-react#98]
[x ] I am running the latest version
[x] I checked the documentation and found no answer
[x] I checked to make sure that this issue has not already been filed
[ x] I'm reporting the issue to the correct repository (for multi-repository projects)

I have error after run command 'npm start':
Failed to compile.
./src/layouts/Admin.js
TypeError: Cannot read property 'type' of undefined
Occurred while linting /material-dashboard-react/src/layouts/Admin.js:43
    at Array.forEach (<anonymous>)

**Comment by EINazare** [comment]
Hello there, @Pirantul ,

Thank you for your interest in working with our products.
This is actually an error from the react-scripts package, here is the link to the mentioned issue: https://github.com/facebook/create-react-app/issues/7753
To solve the issue, please run the following: `npm i -E eslint@6.4.0`.

Best,
Manu

**Comment by phal0r** [comment]
I got a different error:
```
node_modules/eslint/lib/rules/no-octal-escape.js:41
                    /^(?:[^\\]|\\.)*?\\([0-3][0-7]{1,2}|[4-7][0-7]|0(?=[89])|[1-7])/su
                    ^

SyntaxError: Invalid regular expression flags
```
The recommended workaround does fix this problem aswell.
